import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "agriease-language";

const translations = {
  en: {
    common: {
      brandName: "AgriEase",
      brandAlt: "AgriEase - Growing Smarter",
      login: "Login",
      register: "Register",
      joinFarmer: "Join as Farmer",
      joinSupplier: "Join as Supplier",
      alreadyAccount: "Already have an account",
      alreadyMember: "Already a member? Login",
      createAccount: "Create Account",
      createFreeAccount: "Create Free Account",
      language: "Language",
      back: "Back",
      farmer: "Farmer",
      supplier: "Supplier",
      logout: "Logout",
      actions: {
        browseMarket: "Browse Market",
        checkout: "Checkout",
        clearCart: "Clear Cart",
        addToCart: "Add to Cart",
        remove: "Remove",
        continueShopping: "Continue Shopping",
        refresh: "Refresh data",
        viewAll: "View all →",
        editProfile: "Edit Profile",
        saveChanges: "Save Changes",
        cancel: "Cancel",
        cancelOrder: "Cancel Order",
        confirm: "Confirm",
        markDelivered: "Mark Delivered",
        removeHistory: "Remove from History",
        clearFilters: "Clear Filters",
        clearCompleted: "Clear All Completed",
        showActive: "Show Active Only",
        activeOnly: "✓ Active Orders Only",
        placeOrder: "Place Order",
        processing: "Processing...",
        detectDisease: "Detect Disease",
        confirmPayment: "Confirm Payment",
        paymentConfirmed: "Payment Confirmed",
        backToCart: "Back to Cart",
        addProduct: "+ Add Product",
        addEquipment: "+ Add Equipment",
        updateProduct: "Update Product",
        updateEquipment: "Update Equipment",
        delete: "Delete",
        edit: "Edit",
        markAvailable: "Mark Available",
        markUnavailable: "Mark Unavailable",
        switchProfile: "Switch profile",
        switchToFarmer: "Switch to Farmer dashboard",
        switchToSupplier: "Switch to Supplier dashboard",
      },
      accessibility: {
        decreaseQuantity: "Decrease quantity",
        increaseQuantity: "Increase quantity",
      },
      labels: {
        shoppingCart: "Shopping Cart",
        cartSubtitle: "Review and manage your items before checkout",
        cartEmpty: "Your cart is empty",
        product: "Product",
        crop: "Crop",
        equipmentRental: "Equipment Rental",
        rate: "Rate",
        duration: "Duration",
        dates: "Dates",
        orderSummary: "Order Summary",
        totalItems: "Total Items",
        total: "Total",
        paymentMethod: "Payment Method",
        shippingDetails: "Shipping Details",
        fullName: "Full Name",
        email: "Email",
        phoneNumber: "Phone Number",
        address: "Address",
        city: "City",
        state: "State",
        pincode: "Pincode",
        qty: "Qty",
        important: "Important",
        pendingNote: "After payment, your order stays PENDING until supplier confirmation.",
        items: "Items",
        customerDetails: "Farmer Details",
        shippingAddress: "Shipping Address",
        orderDate: "Order Date",
        status: "Status",
        paymentStatus: "Payment Status",
        available: "Available",
        unavailable: "Not Available",
        lastSynced: "Last synced",
        description: "Description",
        prevention: "Prevention",
        confidence: "Confidence",
        note: "Note",
        instructions: "Payment Instructions",
        orderId: "Order ID",
        amount: "Amount",
        transactionId: "UPI Transaction ID *",
        transactionPlaceholder: "Enter 12-digit UTR/Transaction ID",
        transactionValidation: "Transaction ID must be at least 12 characters",
        accountInformation: "Account Information",
        accountType: "Account Type",
        memberSince: "Member Since",
        userId: "User ID",
        changePassword: "Change Password",
        activeRole: "Active Role",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm New Password",
        businessName: "Business Name",
        businessType: "Business Type",
        businessDescription: "Business Description",
        noProducts: "No products available",
        noCrops: "No crops available",
        noTools: "No tools available",
        loadingOrders: "Loading orders...",
        emptyOrders: "No orders yet. Start shopping!",
        paymentPaid: "💳 PAID",
        paymentPending: "💰 Payment Pending",
        orderFiltersStatus: "Order Status",
        orderFiltersPayment: "Payment Status",
        orderFiltersSort: "Sort By",
        orderFiltersShow: "Show Active Only",
        showCount: "Showing",
        of: "of",
        orders: "orders",
      },
    },
    landing: {
      pill: "Smart agriculture ecosystem",
      heroTitle: "Grow faster with",
      heroHighlight: "AgriEase",
      heroImageAlt: "Modern agriculture with smart drone",
      heroDescription:
        "A single platform for equipment rentals, agri-input purchases, and AI-powered crop disease detection designed for real farm workflows.",
      stats: {
        verifiedFarmers: "Verified Farmers",
        supplierListings: "Supplier Listings",
        onTimeDelivery: "On-Time Delivery",
        supportAvailability: "Support Availability",
      },
      features: {
        pill: "Why AgriEase",
        heading: "Purpose-built tools for modern agriculture",
        description:
          "Structured workflows, trusted suppliers, and AI insights so teams can act quickly with confidence.",
        highlights: {
          equipment: {
            title: "Equipment Access",
            text: "Book modern equipment on flexible schedules without high upfront cost.",
          },
          marketplace: {
            title: "Input Marketplace",
            text: "Buy verified seeds, nutrients, and crop-care products from trusted suppliers.",
          },
          ai: {
            title: "AI Disease Detection",
            text: "Upload crop photos and receive instant diagnosis with practical treatment tips.",
          },
        },
      },
      workflow: {
        pill: "How it works",
        heading: "Get started in three clear steps",
        steps: {
          account: {
            title: "Create Your Account",
            detail: "Join as farmer or supplier in under two minutes.",
          },
          discover: {
            title: "Discover Services",
            detail: "Browse products, equipment, and AI crop health tools.",
          },
          manage: {
            title: "Manage Everything",
            detail: "Track bookings, orders, delivery, and payments in one dashboard.",
          },
        },
      },
      cta: {
        pill: "Start today",
        heading: "Bring your farm operations into one reliable platform",
        text: "Improve decisions, reduce delays, and keep your crop lifecycle data connected from field to delivery.",
        button: "Create Free Account",
      },
      nav: {
        mainNavigation: "Main navigation",
        features: "Features",
        howItWorks: "How It Works",
        contact: "Contact",
      },
      footer: {
        loginLink: "Already a member? Login",
        description: "Empowering farmers and suppliers with smart agriculture technology, seamless marketplace access, and AI-powered crop health tools.",
        quickLinks: "Quick Links",
        linkHome: "Home",
        linkFeatures: "Features",
        linkHowItWorks: "How It Works",
        linkLogin: "Login",
        linkRegister: "Register",
        getInTouch: "Get in Touch",
        email: "support@agriease.in",
        phone: "+91 98765 43210",
        address: "Pune, Maharashtra, India",
        followUs: "Follow Us",
        social: {
          facebook: "Facebook",
          twitter: "Twitter",
          instagram: "Instagram",
          youtube: "YouTube",
        },
        copyright: "AgriEase. All rights reserved.",
        madeWith: "Made with",
        madeFor: "for Indian farmers",
      },
    },
    login: {
      title: "Sign in",
      subtitle: "Welcome back to AgriEase.",
      successGreeting: "Welcome back",
      emailLabel: "Email",
      passwordLabel: "Password",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "Enter your password",
      missingFields: "Please enter email and password",
      errorGeneric: "Invalid credentials",
      submit: "Login",
      createAccountCta: "Create an account",
      newHere: "New here?",
      registerLink: "Register",
    },
    register: {
      title: "Join AgriEase",
      subtitle: "Connect with farmers and suppliers.",
      nameLabel: "Full Name",
      emailLabel: "Email",
      mobileLabel: "Mobile Number",
      passwordLabel: "Password",
      namePlaceholder: "Full name",
      emailPlaceholder: "Email address",
      mobilePlaceholder: "Mobile number",
      passwordPlaceholder: "Create password",
      missingFields: "Please fill all required fields and select a role.",
      success: "Registration successful. Please login.",
      errorGeneric: "An error occurred during registration. Try again.",
      submit: "Create Account",
      ghostCta: "Already have an account? Sign in",
    },
    authPage: {
      loginTitle: "Welcome back to AgriEase",
      registerTitle: "Create your AgriEase account",
      loginSubtitle: "Sign in to manage crops, orders, and farm insights.",
      registerSubtitle: "Join the platform to connect farmers and suppliers.",
      imageTitle: "Welcome to AgriEase",
      imageSubtitle: "Cultivating success through smart agriculture technology and seamless connections.",
      imageAlt: "Lush green agricultural crops showing healthy growth",
      backAria: "Back to landing page",
      backToHome: "Back to Home",
      logoAlt: "AgriEase logo",
      tablistAria: "Authentication mode",
      tabLogin: "Login",
      tabRegister: "Register",
    },
    dashboard: {
      nav: {
        home: "Home",
        products: "Products",
        equipment: "Equipment",
        orders: "Orders",
        tools: "Tools",
        crops: "Crops",
        market: "Market",
        disease: "Disease",
        cart: "Cart",
        profile: "Profile",
        cropAdvisor: "AI Crop Advisor",
        landMeasurement: "Land Measurement",
        weeklySchedule: "Weekly Schedule",
      },
      layout: {
        workspace: "workspace",
        goToLanding: "Go to landing",
        closeNavigation: "Close navigation",
        toggleMenu: "Toggle menu",
        openCart: "Open cart",
        notifications: "Notifications",
        settings: "Settings",
      },
    },
    footer: {
      tagline: "Empowering farmers with technology.",
      rights: "All rights reserved.",
    },
    appFooter: {
      copyright: "© 2026 AgriEase",
      privacy: "Privacy",
      terms: "Terms",
      support: "Support",
    },
    theme: {
      dark: "Dark",
      light: "Light",
      switchToDark: "Switch to dark mode",
      switchToLight: "Switch to light mode",
    },
    loader: {
      preparingWorkspace: "Preparing your AgriEase workspace",
    },
    chatbot: {
      eyebrow: "AgriEase AI",
      title: "Need help on the field?",
      closeAria: "Close chatbot",
      welcome: "👋 Hello! I'm your AgriEase AI Assistant. Ask me anything about farming, crops, pests, weather, or agriculture!",
      listen: "Listen",
      placeholder: "Ask about farming, crops, pests...",
      send: "Send",
      launcherAria: "Chat with AgriEase assistant",
      launcherText: "Ask AgriEase",
      responseFailed: "Failed to get response. Please try again.",
      responseFallback: "Sorry, I'm having trouble responding right now. Please try again in a moment.",
    },
    messages: {
      cartEmpty: "Your cart is empty",
      requiredFields: "Please fill all required fields",
      selectImage: "Please upload leaf image",
      predictionFailed: "Prediction failed. Backend not responding.",
      loadOrdersError: "Failed to load orders",
      updateStatusError: "Failed to update status",
      sessionExpired: "Session expired. Please logout and login again.",
      paymentEnterTxn: "Please enter transaction ID",
      paymentTxnLength: "Transaction ID must be at least 12 characters",
      paymentConfirmError: "Failed to confirm payment. Please try again.",
      paymentConfirmed: "Payment confirmed! Waiting for supplier confirmation.",
      imageTooLarge: "Image size should be less than 2MB",
      imageType: "Please select an image file",
      imageReadError: "Failed to read image file",
      profileUpdated: "Profile updated successfully!",
      profileUpdateError: "Failed to update profile",
      passwordMismatch: "New passwords do not match",
      passwordLength: "Password must be at least 6 characters",
      passwordChanged: "Password changed successfully!",
      selectRentalDates: "Select rental dates to proceed",
      endDateInvalid: "End date must be after start date",
      equipmentReserved: "Equipment reserved in cart",
      loadEquipmentError: "Unable to load equipment. Please try again.",
      loadProductsError: "Failed to load products",
      authFailed: "Authentication failed. Please log in again.",
      clearCompletedNone: "No completed orders to clear",
      clearCompletedError: "Failed to clear completed orders",
      unableSync: "Unable to sync with server. Showing cached data.",
      uploadingImage: "Uploading image...",
      roleSwitchFailed: "Unable to switch profile. Please try again.",
    },
    orderTracking: {
      loadError: "Unable to load tracking details",
      loading: "Loading tracking details...",
      noData: "No tracking information available.",
      title: "Order Tracking",
      currentStatus: "Current Status",
      deliveryProgress: "Delivery Progress",
      timeline: "Timeline",
      location: "Location",
      viewProof: "View Delivery Proof",
      statusLabels: {
        pending: "Order Placed",
        confirmed: "Supplier Confirmed",
        assigned: "Agent Assigned",
        pickedUp: "Picked Up",
        outForDelivery: "Out for Delivery",
        delivered: "Delivered",
      },
    },
    status: {
      pending: "PENDING",
      confirmed: "CONFIRMED",
      assigned: "ASSIGNED",
      picked_up: "PICKED UP",
      out_for_delivery: "OUT FOR DELIVERY",
      delivered: "DELIVERED",
      cancelled: "CANCELLED",
      failed_delivery: "FAILED DELIVERY",
      returned: "RETURNED",
      healthy: "Healthy",
      monitor: "Monitor",
      attention: "Needs Attention",
    },
    farmer: {
      checkout: {
        title: "Checkout",
        subtitle: "Complete your order",
        alertText: "After payment, your order stays PENDING until supplier confirmation.",
        confirmTitle: "Confirm your order?",
        confirmItems: "Items",
        confirmTotal: "Total Amount",
        confirmPayment: "Payment Method",
        confirmDelivery: "Delivery to",
        confirmCta: "Click OK to place order",
        upiOption: "UPI QR Code",
        codOption: "Cash on Delivery",
        emptyTitle: "Your cart is empty",
        emptyAction: "Continue Shopping",
        toastSuccess: "Order placed. Waiting for supplier confirmation.",
        toastError: "Failed to place order",
        toastOutdatedCartItems: "Some cart items are outdated. Please clear cart and add items again.",
        toastMixedSuppliers: "Your cart has items from multiple suppliers. Please place separate orders.",
      },
      crops: {
        title: "Buy Crops",
        subtitle: "Fresh inputs curated by suppliers.",
        empty: "No crops available",
      },
      market: {
        title: "Marketplace",
        subtitle: "Add supplies and place orders in minutes.",
        empty: "No products available",
        categories: "Categories",
        all: "All",
        sortBy: "Sort by",
        other: "Other",
        sort: {
          default: "Default",
          nameAsc: "Name A-Z",
          priceLowHigh: "Price: Low to High",
          priceHighLow: "Price: High to Low",
        },
      },
      home: {
        loading: "Loading farmer dashboard",
        heroKicker: "Farm operations",
        heroSubtitle: "Stay on top of your fields, equipment, and market activity from one screen.",
        heroGreetingPrefix: "Welcome back",
        heroChipOverview: "Farm overview",
        heroChipCropsTracked: "crops tracked",
        heroChipOrdersInFlow: "orders in market flow",
        openCropAdvisor: "Open crop advisor",
        shortcutsTitle: "Farmer shortcuts",
        liveActivityKicker: "Live activity",
        fieldPulseTitle: "Field pulse",
        detailsKicker: "Overview",
        farmDetailsTitle: "Farm details",
        refresh: "Refresh data",
        addFarmSize: "Add in profile",
        defaultCrops: {
          rice: "Rice",
          wheat: "Wheat",
        },
        activity: {
          active: "active",
          running: "running",
          ordersMoving: "Market requests are moving through checkout.",
          noActiveOrders: "No active market orders yet.",
          equipmentInProgress: "Equipment bookings are still in progress.",
          rentalClear: "Rental schedule is clear today.",
          cropStable: "Crop conditions look stable this week.",
          cropMonitor: "A few crops may need monitoring.",
        },
        stat: {
          farmSize: { label: "Farm Size", helper: "Your cultivated land" },
          avgHealth: { label: "Avg Health", helper: "Crop vitality" },
          marketOrders: { label: "Market Orders", helper: "Placed this season" },
          rentals: { label: "Active Rentals", helper: "Equipment on field" },
        },
        quick: {
          market: { title: "Browse Market", subtitle: "Seeds, inputs and supplies" },
          tools: { title: "Rent Equipment", subtitle: "Book verified machines" },
          disease: { title: "Disease Detection", subtitle: "AI crop scans" },
          orders: { title: "My Orders", subtitle: "Track deliveries" },
        },
        cropsSection: {
          kicker: "Crop Health Summary",
          title: "Monitor your fields",
          cta: "View all →",
          acres: "acres",
          statuses: {
            healthy: "Healthy",
            monitor: "Monitor",
            attention: "Attention",
          },
        },
      },
      disease: {
        title: "Plant Disease Detection",
        subtitle: "Upload a leaf image to detect disease.",
        uploadLabel: "Upload leaf image",
        button: "Detect Disease",
        description: "Description",
        prevention: "Prevention",
        confidence: "Confidence",
        buyLink: "Buy Recommended Supplement",
      },
      orders: {
        title: "My Orders",
        subtitle: "Track your order and booking history",
        empty: "No orders yet. Start shopping!",
        toastCancelled: "Order cancelled successfully",
        cancelling: "Cancelling...",
        status: {
          pendingPaid: "Waiting for supplier confirmation",
          pendingUnpaid: "Pending payment & supplier confirmation",
          confirmed: "Confirmed by supplier - Being prepared",
          assigned: "Delivery agent assigned",
          pickedUp: "Picked up from supplier",
          outForDelivery: "Out for delivery",
          delivered: "Delivered",
          cancelled: "Cancelled",
        },
      },
      payment: {
        title: "Complete Payment",
        subtitle: "Scan QR code to pay via UPI",
        amountToPay: "Amount to Pay",
        upiPayment: "UPI Payment",
        completeWithin: "Complete payment within",
        scanQrPrompt: "Scan QR with any UPI app",
        payTo: "Pay to",
        supportedApps: "PhonePe • GPay • Paytm • BHIM",
        verifying: "Verifying Payment...",
        securityNote: "Your payment is secured with 256-bit SSL encryption",
        note: "After payment, your order will be PENDING until the supplier confirms it.",
        instructionsTitle: "Payment Instructions:",
        steps: {
          one: "Open any UPI app (GPay, PhonePe, Paytm, BHIM, etc.)",
          two: 'Tap "Scan QR" and scan the QR code above',
          three: "Verify the amount:",
          four: "Complete the payment using your UPI PIN",
          five: "Copy the 12-digit Transaction/UTR ID from your app",
          six: 'Enter the Transaction ID below and click "Confirm Payment"',
        },
        amountPrefix: "INR",
        button: "Confirm Payment",
        back: "Back to Cart",
      },
      profile: {
        title: "My Profile",
        subtitle: "Manage your account information",
        role: "Farmer",
        deleteConfirm: "Delete your account permanently? This will remove your profile and related data. This action cannot be undone.",
        avatarHint: 'Click "Edit Profile" to change photo',
        changePhoto: "Change Photo",
        removePhoto: "Remove",
        statsError: "Unable to sync stats right now. Showing last known values.",
        accountStatsTitle: "Account Statistics",
        stats: {
          totalOrders: "Market Orders",
          equipmentBookings: "Equipment Bookings",
          activeBookings: "Active Rentals",
          diseaseScans: "Disease Scans",
          activeNow: "Active now",
        },
        placeholders: {
          phone: "Enter phone number",
          address: "Enter your address",
          farmSize: "e.g., 5 acres",
          cropTypes: "e.g., Rice, Wheat, Vegetables",
        },
        form: {
          farmSizeLabel: "Farm Size (in acres)",
          cropTypesLabel: "Crop Types",
        },
      },
      account: {
        title: "My Profile",
        subtitle: "Manage your account information",
        role: "Farmer",
      },
      tools: {
        title: "Rent Tools",
        subtitle: "Reserve equipment with flexible dates.",
        loading: "Loading equipment...",
        empty: "No tools available",
        available: "Available",
        unavailable: "Not Available",
      },
      cropAdvisor: {
        title: "AI Crop Advisor",
        subtitle: "Weather-driven crop suitability with percentage-based recommendations.",
        findCrops: "Find crops for your weather",
        enterLocation: "Enter village or city",
        useCurrentLocation: "Use Current Location",
        locating: "Locating...",
        generate: "Generate",
        analyzing: "Analyzing...",
        result: "Result",
        humidity: "humidity",
        generateAiAdvisory: "Generate AI Advisory",
        generatingAiAdvice: "Generating AI Advice...",
        suitability: "suitability",
        recentRecommendations: "Recent recommendations",
        noHistory: "No recommendation history yet.",
        toastSuccess: "Crop recommendations generated",
        toastError: "Failed to generate recommendation",
        toastAiError: "Unable to generate AI advisory",
        toastEnterLocation: "Please enter location",
        toastLocationSelected: "Current location selected",
        toastLocationError: "Unable to fetch location",
        networkLocation: "Using network location (IP based)",
      },
      landMeasurement: {
        title: "Live GPS Land Measurement",
        subtitle: "Click on the map to mark boundary points and calculate area in acres.",
        optionalLabel: "Optional label (e.g., West field)",
        useCurrentLocation: "Use Current Location",
        locating: "Locating...",
        addCurrentPoint: "Add Current Point",
        clear: "Clear",
        saveMeasurement: "Save Measurement",
        saving: "Saving...",
        street: "Street",
        satellite: "Satellite",
        points: "Points",
        area: "Area",
        acres: "acres",
        recentMeasurements: "Recent measurements",
        noMeasurements: "No saved measurements.",
        unnamedField: "Unnamed field",
        toastMinPoints: "Please mark at least 4 points",
        toastSaved: "Land measurement saved",
        toastSaveError: "Failed to save land measurement",
        toastCentered: "Map centered to current location",
        toastPointAdded: "Current location added as point",
        toastNetworkPoint: "Network location added as point",
        toastLocationError: "Unable to fetch location",
        networkLocation: "Using network location (IP based)",
      },
      weeklySchedule: {
        title: "AI Weekly Crop Schedule",
        subtitle: "Generate organic or inorganic week-wise farm activity plans and export to PDF.",
        crop: "Crop",
        planType: "Plan Type",
        organic: "Organic",
        inorganic: "Inorganic",
        totalWeeks: "Total Weeks",
        landArea: "Land Area (acres)",
        generatePlan: "Generate Weekly Plan",
        generating: "Generating...",
        generateAiSummary: "Generate AI Summary",
        generatingAiSummary: "Generating AI Summary...",
        exportPdf: "Export PDF",
        plan: "plan",
        week: "Week",
        savedHistory: "Saved schedule history",
        noSchedules: "No schedules generated yet.",
        weeks: "weeks",
        toastSuccess: "Weekly schedule generated",
        toastError: "Failed to generate schedule",
        toastAiError: "Unable to generate AI summary",
        pdfTitle: "AgriEase Weekly Plan",
        pdfType: "Type",
        pdfArea: "Area",
      },
    },
    supplier: {
      home: {
        loading: "Loading supplier dashboard",
        kicker: "Supplier operations",
        heroSubtitle: "Track live orders, keep your listings updated, and keep dispatch performance easy to scan.",
        heroChips: {
          productsLive: "products live",
          equipmentItems: "equipment items",
          pendingApprovals: "pending approvals",
        },
        openOrderCenter: "Open order center",
        actionsKicker: "Actions",
        shortcutsTitle: "Supplier shortcuts",
        pipelineKicker: "Order pipeline",
        pipelineTitle: "Newest farmer requests",
        noOrdersYet: "No orders yet. Promote your listings to get started.",
        and: "and",
        commercialKicker: "Commercial overview",
        commercialTitle: "Revenue and order momentum",
        inventoryKicker: "Inventory snapshot",
        inventoryTitle: "Keep supply ready",
        updateCatalog: "Update catalog",
        detailsKicker: "Details",
        businessOverview: "Business overview",
        openProfile: "Open profile",
        stats: {
          productsLive: "Products live",
          crops: "crops",
          and: "and",
          supplies: "supplies",
          equipmentFleet: "Equipment fleet",
          availableToday: "available today",
          pendingOrders: "Pending orders",
          fulfillmentRate: "fulfillment rate",
          revenueMonth: "Revenue (month)",
          totalOrders: "total orders",
        },
        quick: {
          manageProducts: { title: "Manage Products", subtitle: "List crops and agri-inputs" },
          manageEquipment: { title: "Manage Equipment", subtitle: "Rent tractors and tools" },
          reviewOrders: { title: "Review Orders", subtitle: "Confirm and dispatch" },
          editProfile: { title: "Edit Profile", subtitle: "Update business info" },
        },
        inventory: {
          topProducts: "Top products",
          addBestSellers: "Add your best sellers",
          skusListed: "SKUs listed",
          equipmentRates: "Equipment rates",
          avgPerDay: "avg/day",
          noEquipment: "No equipment added yet",
          avgOrderValue: "Avg order value",
          fulfilledOrders: "fulfilled orders",
        },
        spotlight: {
          catalogCoverage: "Live catalog coverage",
          activeListings: "active listings",
          cropFocusedAvailable: "crop-focused products are available to farmers.",
          addCropProducts: "Add crop products to improve catalog breadth.",
          equipmentReadiness: "Equipment readiness",
          ready: "ready",
          fleetRealtime: "Fleet availability is visible to farmers in real time.",
          addRentalEquipment: "Add rental equipment to unlock booking demand.",
          orderFulfillment: "Order fulfillment",
          ordersNeedAction: "orders still need action.",
          allOnPace: "All tracked orders are currently on pace.",
        },
        business: {
          totalRevenue: "Total revenue",
          monthRevenue: "Month revenue",
          avgOrderTicket: "Avg order ticket",
          fulfillmentRate: "Fulfillment rate",
        },
      },
      products: {
        title: "Manage Products",
        subtitle: "Add and manage your product listings",
        catalogTitle: "Product Catalog",
        catalogSubtitle: "Keep your supplier inventory up to date",
        empty: "No products yet. Click \"Add Product\" to get started!",
        noDescription: "No description",
        confirm: {
          delete: "Are you sure you want to delete this product?",
        },
        toast: {
          added: "Product added successfully!",
          updated: "Product updated successfully!",
          deleted: "Product deleted successfully!",
          saveError: "Failed to save product",
          deleteError: "Failed to delete product",
        },
        form: {
          addTitle: "Add New Product",
          editTitle: "Edit Product",
          productName: "Product Name",
          productNamePlaceholder: "e.g., Organic Fertilizer",
          descriptionPlaceholder: "Product description",
          price: "Price",
          type: "Type",
          image: "Product Image",
        },
        types: {
          cropSeeds: "Crop/Seeds",
          fertilizer: "Fertilizer",
          pesticide: "Pesticide",
        },
      },
      equipment: {
        title: "Manage Equipment",
        subtitle: "Add and manage equipment for rental",
        fleetTitle: "Equipment Fleet",
        fleetSubtitle: "Track availability and pricing of rental items",
        empty: "No equipment yet. Click \"Add Equipment\" to get started!",
        noDescription: "No description",
        confirm: {
          delete: "Are you sure you want to delete this equipment?",
        },
        toast: {
          added: "Equipment added successfully!",
          updated: "Equipment updated successfully!",
          deleted: "Equipment deleted successfully!",
          saveError: "Failed to save equipment",
          deleteError: "Failed to delete equipment",
          notFound: "Equipment not found",
          availabilityUpdated: "Availability updated!",
          availabilityError: "Failed to update availability",
        },
        form: {
          addTitle: "Add New Equipment",
          editTitle: "Edit Equipment",
          name: "Equipment Name",
          namePlaceholder: "e.g., Tractor",
          descriptionPlaceholder: "Equipment description",
          dailyRate: "Daily Rate",
          image: "Equipment Image",
          availableForRent: "Available for rent",
        },
      },
      orders: {
        title: "Incoming Orders",
        subtitle: "Manage farmer orders, assignments, and delivery progress",
        controlCenter: "Order Control Center",
        controlSubtitle: "Filter, sort, and act on order pipeline",
        allStatuses: "All Statuses",
        allPayments: "All Payments",
        noOrders: "No orders yet.",
        noOrdersForFilter: "No orders match your filters.",
        assignedAgent: "Assigned Delivery Agent",
        notAssigned: "Not assigned",
        rejectionReason: "Rejection Reason",
        noRejectionReason: "No reason provided by agent.",
        confirmOrder: "Confirm Order",
        selectDeliveryAgent: "Select Delivery Agent",
        selectDeliveryAgentFirst: "Select a delivery agent first",
        assignAgent: "Assign Agent",
        reassignAgent: "Reassign Agent",
        sort: {
          newestFirst: "Newest First",
          oldestFirst: "Oldest First",
          highestAmount: "Highest Amount",
          lowestAmount: "Lowest Amount",
        },
        toast: {
          confirmedAndAssigned: "Order confirmed and delivery agent assigned",
          statusUpdated: "Order updated successfully",
          removedFromHistory: "Order removed from history",
          removeError: "Failed to remove order",
          agentAssigned: "Delivery agent assigned successfully",
          assignError: "Failed to assign agent",
          removedSome: "Completed orders removed from history",
          failedSome: "Some completed orders could not be removed",
        },
      },
      profile: {
        title: "My Profile",
        subtitle: "Manage your business account and view statistics",
        accountSubtitle: "Update profile, security, and account details",
        personalInfo: "Personal Information",
        businessDetails: "Business Details",
        businessStatistics: "Business Statistics",
        phonePlaceholder: "Enter phone number",
        addressPlaceholder: "Enter your business address",
        descriptionPlaceholder: "Describe your business and products",
        businessNamePlaceholder: "e.g., ABC Agri Supplies",
        selectBusinessType: "Select business type",
        updatePassword: "Update Password",
        changePasswordFailed: "Failed to change password",
        changePhoto: "Change Photo",
        removePhoto: "Remove",
        deleteAccount: "Delete Account",
        statsError: "Unable to load live stats right now",
        accountDeleted: "Account deleted successfully",
        deleteAccountFailed: "Failed to delete account",
        loadProfileFailed: "Failed to load profile",
        stats: {
          productsListed: "Products Listed",
          equipmentListed: "Equipment Listed",
          totalSales: "Total Sales",
          totalOrders: "Total Orders",
        },
        businessTypes: {
          equipmentRental: "Equipment Rental",
          seedsAndFertilizers: "Seeds & Fertilizers",
          pesticides: "Pesticides",
          generalSupplies: "General Supplies",
          other: "Other",
        },
      },
    },
    agent: {
      dashboard: {
        deliveryAgent: "Delivery Agent",
        notProvided: "Not provided",
        localServiceArea: "Local Service Area",
        defaultVehicleName: "Agri Van",
        defaultSupplierName: "AgriEase Supplier",
        defaultProductName: "Farm Produce",
        workspace: "Delivery operations workspace",
        portal: "Delivery Agent Portal",
        kicker: "Delivery operations",
        title: "Delivery Agent Dashboard",
        subtitle: "AgriEase logistics control panel for live delivery operations.",
        assigned: "assigned",
        inTransit: "in transit",
        completed: "completed",
        refreshOrders: "Refresh Orders",
        closeEdit: "Close Edit",
        lastUpdated: "Last updated",
        loadOrdersFailed: "Failed to load assigned orders",
        profileDeleted: "Profile deleted successfully",
        deleteProfileFailed: "Failed to delete profile",
        orderUpdated: "Order updated",
        chooseImageFirst: "Choose an image first",
        proofUploaded: "Delivery proof uploaded",
        proofUploadFailed: "Proof upload failed",
        paymentCollected: "COD payment collected successfully",
        collectPaymentFailed: "Failed to collect payment",
        loadingDashboard: "Loading delivery dashboard",
        deleteConfirm: "Delete your account permanently? This action cannot be undone.",
        rejectPrompt: "Optional: add a reason for rejecting this order (supplier will see it).",
        orderRejected: "Order rejected",
        supplierLocationFallback: "Supplier location",
        farmerLocationFallback: "Farmer location",
        routeOverview: "Route overview",
        liveRouteMap: "Live route map",
        tracking: "Tracking",
        selectOrderForMap: "Select an order to load supplier and farmer map.",
        mapTitle: "Delivery Route Map",
        agentSnapshot: "Agent snapshot",
        vehicle: "Vehicle",
        vehicleNo: "Vehicle No",
        serviceArea: "Service Area",
        rating: "Rating",
        operationsPulse: "Operations pulse",
        incomingRequests: "Incoming requests",
        acceptedOrders: "Accepted orders",
        selectedOrder: "Selected order",
        none: "None",
        paymentTracking: "Payment tracking",
        codFollowUps: "COD follow-ups",
        completedDeliveries: "Completed deliveries",
        assignedOrders: "Assigned Orders",
        pendingRequests: "Pending Requests",
        inTransitOrders: "In Transit Orders",
        deliveredToday: "Delivered Today",
        dispatchAnalytics: "Dispatch analytics",
        dailyDeliveryLoad: "Daily delivery load",
        liveStats: "Live stats",
        deliveryStatusDetails: "Delivery status details",
        selectOrderForProgress: "Select an order to view progress.",
        trackingOrder: "Tracking order",
        for: "for",
        moveToNextStage: "Move to Next Stage",
        uploadDeliveryPhoto: "Upload Delivery Photo",
        codOrder: "COD Order",
        markPaymentCollected: "Mark Payment Collected",
        paymentCollectedLabel: "Payment collected",
        profileTitle: "Delivery Agent Profile",
        incomingRequestsTitle: "Incoming Delivery Requests",
        noIncomingRequests: "No incoming requests.",
        noAcceptedOrders: "No accepted orders yet.",
        navigation: "Navigation",
        collectPayment: "Collect Payment",
        collect: "Collect",
        paid: "PAID",
        pending: "PENDING",
        codBadge: "COD",
        upiBadge: "UPI",
        actionPickedUp: "Picked Up",
        actionOutForDelivery: "Out For Delivery",
        actionDelivered: "Delivered",
        deliveryHistory: "Delivery History",
        deliveryDate: "Delivery Date",
        deliveryProof: "Delivery Proof",
        viewProof: "View Proof",
        noProofUploaded: "No proof uploaded",
        noHistory: "No delivery history yet.",
        loadingAssignedOrders: "Loading assigned orders...",
        noAssignedOrders: "No assigned orders found.",
        footerLine1: "Smart delivery operations.",
        footerLine2: "Keeping supplier dispatch and farmer deliveries coordinated.",
        chart: {
          assigned: "Assigned",
          pending: "Pending",
          transit: "Transit",
          delivered: "Delivered",
        },
        table: {
          supplierName: "Supplier Name",
          farmerName: "Farmer Name",
          product: "Product",
          deliveryAddress: "Delivery Address",
          accept: "Accept",
          reject: "Reject",
          viewDetails: "View Details",
          updateStatus: "Update Status",
          navigation: "Navigation",
        },
      },
    },
  },
  mr: {
    common: {
      brandName: "AgriEase",
      brandAlt: "अॅग्रीईज - स्मार्ट शेतीचे भविष्य",
      login: "लॉगिन",
      register: "नोंदणी करा",
      joinFarmer: "शेतकरी म्हणून सामील व्हा",
      joinSupplier: "पुरवठादार म्हणून सामील व्हा",
      alreadyAccount: "आधीच खाते आहे",
      alreadyMember: "आधीच सदस्य आहात? लॉगिन",
      createAccount: "खाते तयार करा",
      createFreeAccount: "विनामूल्य खाते तयार करा",
      language: "भाषा",
      back: "मागे",
      farmer: "शेतकरी",
      supplier: "पुरवठादार",
      logout: "लॉगआउट",
      actions: {
        browseMarket: "मार्केट पहा",
        checkout: "चेकआउट",
        clearCart: "कार्ट रिकामे करा",
        addToCart: "कार्टमध्ये जोडा",
        remove: "काढून टाका",
        continueShopping: "खरेदी सुरू ठेवा",
        refresh: "डेटा रीफ्रेश करा",
        viewAll: "सर्व पहा →",
        editProfile: "प्रोफाइल संपादित करा",
        saveChanges: "बदल जतन करा",
        cancel: "रद्द करा",
        cancelOrder: "ऑर्डर रद्द करा",
        confirm: "निश्चित करा",
        markDelivered: "डिलिव्हर झाले म्हणून चिन्हांकित करा",
        removeHistory: "इतिहासातून काढा",
        clearFilters: "फिल्टर्स काढा",
        clearCompleted: "संपलेल्या ऑर्डर्स काढा",
        showActive: "फक्त सक्रिय दाखवा",
        activeOnly: "✓ फक्त सक्रिय ऑर्डर्स",
        placeOrder: "ऑर्डर करा",
        processing: "प्रक्रिया सुरू...",
        detectDisease: "रोग शोधा",
        confirmPayment: "पेमेंट निश्चित करा",
        paymentConfirmed: "पेमेंट निश्चित झाले",
        backToCart: "कार्टकडे परत",
        addProduct: "+ उत्पादन जोडा",
        addEquipment: "+ उपकरण जोडा",
        updateProduct: "उत्पादन अपडेट करा",
        updateEquipment: "उपकरण अपडेट करा",
        delete: "हटवा",
        edit: "संपादित करा",
        markAvailable: "उपलब्ध दाखवा",
        markUnavailable: "उपलब्ध नाही दाखवा",
        switchProfile: "प्रोफाइल बदला",
        switchToFarmer: "शेतकरी डॅशबोर्डवर जा",
        switchToSupplier: "पुरवठादार डॅशबोर्डवर जा",
      },
      accessibility: {
        decreaseQuantity: "प्रमाण कमी करा",
        increaseQuantity: "प्रमाण वाढवा",
      },
      labels: {
        shoppingCart: "खरेदी कार्ट",
        cartSubtitle: "चेकआउटपूर्वी वस्तू तपासा आणि व्यवस्थापित करा",
        cartEmpty: "तुमचा कार्ट रिकामा आहे",
        product: "उत्पादन",
        crop: "पीक",
        equipmentRental: "उपकरण भाडे",
        rate: "दर",
        duration: "कालावधी",
        dates: "तारखा",
        orderSummary: "ऑर्डर सारांश",
        totalItems: "एकूण वस्तू",
        total: "एकूण",
        paymentMethod: "पेमेंट पद्धत",
        shippingDetails: "शिपिंग तपशील",
        fullName: "पूर्ण नाव",
        email: "ईमेल",
        phoneNumber: "फोन क्रमांक",
        address: "पत्ता",
        city: "शहर",
        state: "राज्य",
        pincode: "पिनकोड",
        qty: "प्रमाण",
        important: "महत्त्वाचे",
        pendingNote: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत तुमची ऑर्डर PENDING राहील.",
        items: "वस्तू",
        customerDetails: "शेतकरी तपशील",
        shippingAddress: "शिपिंग पत्ता",
        orderDate: "ऑर्डर तारीख",
        status: "स्थिती",
        paymentStatus: "पेमेंट स्थिती",
        available: "उपलब्ध",
        unavailable: "उपलब्ध नाही",
        lastSynced: "शेवटचे सिंक",
        description: "वर्णन",
        prevention: "प्रतिबंध",
        confidence: "विश्वास पातळी",
        note: "टिप",
        instructions: "पेमेंट सूचना",
        orderId: "ऑर्डर क्रमांक",
        amount: "रक्कम",
        transactionId: "UPI व्यवहार क्रमांक *",
        transactionPlaceholder: "१२ अंकी UTR/Transaction ID भरा",
        transactionValidation: "Transaction ID किमान १२ अक्षरांचा हवा",
        accountInformation: "खाते माहिती",
        accountType: "खात्याचा प्रकार",
        memberSince: "सदस्यता दिनांक",
        userId: "वापरकर्ता क्रमांक",
        changePassword: "पासवर्ड बदला",
        activeRole: "सक्रिय भूमिका",
        currentPassword: "सध्याचा पासवर्ड",
        newPassword: "नवीन पासवर्ड",
        confirmPassword: "नवीन पासवर्ड पुन्हा भरा",
        businessName: "व्यवसायाचे नाव",
        businessType: "व्यवसाय प्रकार",
        businessDescription: "व्यवसाय वर्णन",
        noProducts: "कोणतीही उत्पादने उपलब्ध नाहीत",
        noCrops: "कोणतीही पिके उपलब्ध नाहीत",
        noTools: "कोणतीही साधने उपलब्ध नाहीत",
        loadingOrders: "ऑर्डर्स लोड होत आहेत...",
        emptyOrders: "अद्याप कोणतीही ऑर्डर नाही. खरेदी सुरू करा!",
        paymentPaid: "💳 पेमेंट झाले",
        paymentPending: "💰 पेमेंट प्रलंबित",
        orderFiltersStatus: "ऑर्डर स्थिती",
        orderFiltersPayment: "पेमेंट स्थिती",
        orderFiltersSort: "क्रम लावा",
        orderFiltersShow: "फक्त सक्रिय दाखवा",
        showCount: "दाखवत आहोत",
        of: "पैकी",
        orders: "ऑर्डर्स",
      },
    },
    landing: {
      pill: "स्मार्ट शेती इकोसिस्टम",
      heroTitle: "अधिक वेगाने वाढवा",
      heroHighlight: "AgriEase",
      heroImageAlt: "स्मार्ट ड्रोनसह आधुनिक शेती",
      heroDescription:
        "उपकरण भाडे, कृषी इनपुट खरेदी आणि एआय रोग निदानासाठी एकच प्लॅटफॉर्म.",
      stats: {
        verifiedFarmers: "सत्यापित शेतकरी",
        supplierListings: "पुरवठादार सूची",
        onTimeDelivery: "वेळेवर वितरण",
        supportAvailability: "२४/७ समर्थन",
      },
      features: {
        pill: "अॅग्रीईज का?",
        heading: "आधुनिक शेतीसाठी तयार केलेली साधने",
        description:
          "संरचित वर्कफ्लो, विश्वासू पुरवठादार आणि एआय इनसाइट्समुळे टीमला जलद निर्णय घेता येतात.",
        highlights: {
          equipment: {
            title: "उपकरण उपलब्धता",
            text: "मोठा खर्च न करता आधुनिक उपकरणे सोयीच्या वेळांना बुक करा.",
          },
          marketplace: {
            title: "इनपुट मार्केटप्लेस",
            text: "विश्वासार्ह पुरवठादारांकडून बी-बियाणे, पोषक तत्त्वे आणि पिक संरक्षण खरेदी करा.",
          },
          ai: {
            title: "एआय रोग निदान",
            text: "पीकांचे फोटो अपलोड करा आणि त्वरित निदान तसेच उपचाराचा सल्ला मिळवा.",
          },
        },
      },
      workflow: {
        pill: "कसे कार्य करते",
        heading: "फक्त तीन टप्प्यात सुरुवात",
        steps: {
          account: {
            title: "तुमचे खाते तयार करा",
            detail: "२ मिनिटांत शेतकरी किंवा पुरवठादार म्हणून सामील व्हा.",
          },
          discover: {
            title: "सेवा शोधा",
            detail: "उत्पादने, उपकरणे आणि एआय पीक आरोग्य साधने ब्राउझ करा.",
          },
          manage: {
            title: "सर्वकाही सांभाळा",
            detail: "बुकिंग, ऑर्डर, वितरण आणि पेमेंट एकाच डॅशबोर्डवर ट्रॅक करा.",
          },
        },
      },
      cta: {
        pill: "आजच सुरू करा",
        heading: "आपली शेती ऑपरेशन्स एका विश्वासार्ह प्लॅटफॉर्मवर आणा",
        text: "निर्णय सुधारवा, विलंब कमी करा आणि शेतापासून वितरणापर्यंतची माहिती जोडलेली ठेवा.",
        button: "विनामूल्य खाते तयार करा",
      },
      nav: {
        mainNavigation: "मुख्य नेव्हिगेशन",
        features: "वैशिष्ट्ये",
        howItWorks: "कसे कार्य करते",
        contact: "संपर्क",
      },
      footer: {
        loginLink: "आधीच सदस्य आहात? लॉगिन",
        description: "स्मार्ट शेती तंत्रज्ञान, सुलभ बाजारपेठ आणि एआय पीक आरोग्य साधनांसह शेतकरी आणि पुरवठादारांना सामर्थ्य देणे.",
        quickLinks: "जलद दुवे",
        linkHome: "मुख्यपृष्ठ",
        linkFeatures: "वैशिष्ट्ये",
        linkHowItWorks: "कसे कार्य करते",
        linkLogin: "लॉगिन",
        linkRegister: "नोंदणी",
        getInTouch: "संपर्क करा",
        email: "support@agriease.in",
        phone: "+91 98765 43210",
        address: "पुणे, महाराष्ट्र, भारत",
        followUs: "आम्हाला फॉलो करा",
        social: {
          facebook: "फेसबुक",
          twitter: "ट्विटर",
          instagram: "इंस्टाग्राम",
          youtube: "यूट्यूब",
        },
        copyright: "AgriEase. सर्व हक्क राखीव.",
        madeWith: "",
        madeFor: "भारतीय शेतकऱ्यांसाठी बनवले",
      },
    },
    login: {
      title: "लॉगिन करा",
      subtitle: "अॅग्रीईजवर परत स्वागत आहे.",
      successGreeting: "पुन्हा स्वागत आहे",
      emailLabel: "ईमेल",
      passwordLabel: "पासवर्ड",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "तुमचा पासवर्ड टाका",
      missingFields: "कृपया ईमेल आणि पासवर्ड भरा",
      errorGeneric: "चुकीची ओळख माहिती",
      submit: "लॉगिन",
      createAccountCta: "खाते तयार करा",
      newHere: "इथे नवीन आहात?",
      registerLink: "नोंदणी करा",
    },
    register: {
      title: "अॅग्रीईजमध्ये सामील व्हा",
      subtitle: "शेतकरी आणि पुरवठादार यांना जोडा.",
      nameLabel: "पूर्ण नाव",
      emailLabel: "ईमेल",
      mobileLabel: "मोबाइल क्रमांक",
      passwordLabel: "पासवर्ड",
      namePlaceholder: "पूर्ण नाव",
      emailPlaceholder: "ईमेल पत्ता",
      mobilePlaceholder: "मोबाइल क्रमांक",
      passwordPlaceholder: "पासवर्ड तयार करा",
      missingFields: "कृपया सर्व माहिती भरा आणि भूमिका निवडा.",
      success: "नोंदणी यशस्वी. कृपया लॉगिन करा.",
      errorGeneric: "नोंदणीदरम्यान त्रुटी आली. पुन्हा प्रयत्न करा.",
      submit: "खाते तयार करा",
      ghostCta: "आधीच खाते आहे? लॉगिन करा",
    },
    authPage: {
      loginTitle: "AgriEase मध्ये पुन्हा स्वागत",
      registerTitle: "तुमचे AgriEase खाते तयार करा",
      loginSubtitle: "पिके, ऑर्डर्स आणि शेती माहिती व्यवस्थापित करण्यासाठी लॉगिन करा.",
      registerSubtitle: "शेतकरी आणि पुरवठादारांना जोडण्यासाठी प्लॅटफॉर्ममध्ये सामील व्हा.",
      imageTitle: "AgriEase मध्ये स्वागत आहे",
      imageSubtitle: "स्मार्ट शेती तंत्रज्ञान आणि सहज जोडण्याद्वारे यशाची शेती.",
      imageAlt: "हिरवीगार आणि निरोगी वाढ दाखवणारी शेती",
      backAria: "मुख्य पानावर परत जा",
      backToHome: "मुख्यपृष्ठावर परत",
      logoAlt: "AgriEase लोगो",
      tablistAria: "प्रमाणीकरण मोड",
      tabLogin: "लॉगिन",
      tabRegister: "नोंदणी",
    },
    dashboard: {
      nav: {
        home: "मुख्यपृष्ठ",
        products: "उत्पादने",
        equipment: "उपकरणे",
        orders: "ऑर्डर्स",
        tools: "साधने",
        crops: "पिके",
        market: "बाजार",
        disease: "रोग",
        cart: "कार्ट",
        profile: "प्रोफाइल",
        cropAdvisor: "एआय पीक सल्लागार",
        landMeasurement: "जमीन मोजणी",
        weeklySchedule: "साप्ताहिक वेळापत्रक",
      },
      layout: {
        workspace: "कार्यस्थान",
        goToLanding: "मुख्य पानावर जा",
        closeNavigation: "नेव्हिगेशन बंद करा",
        toggleMenu: "मेनू टॉगल करा",
        openCart: "कार्ट उघडा",
        notifications: "सूचना",
        settings: "सेटिंग्ज",
      },
    },
    footer: {
      tagline: "तंत्रज्ञानाद्वारे शेतकऱ्यांना सामर्थ्य द्या.",
      rights: "सर्व हक्क राखीव.",
    },
    appFooter: {
      copyright: "© 2026 AgriEase",
      privacy: "गोपनीयता",
      terms: "अटी",
      support: "मदत",
    },
    theme: {
      dark: "डार्क",
      light: "लाइट",
      switchToDark: "डार्क मोडवर बदला",
      switchToLight: "लाइट मोडवर बदला",
    },
    loader: {
      preparingWorkspace: "तुमचे AgriEase कार्यस्थान तयार करत आहोत",
    },
    chatbot: {
      eyebrow: "AgriEase AI",
      title: "शेतात मदत हवी आहे का?",
      closeAria: "चॅटबॉट बंद करा",
      welcome: "👋 नमस्कार! मी तुमचा AgriEase AI सहाय्यक आहे. शेती, पिके, कीड, हवामान किंवा कृषीविषयक काहीही विचारा!",
      listen: "ऐका",
      placeholder: "शेती, पिके, कीड याबद्दल विचारा...",
      send: "पाठवा",
      launcherAria: "AgriEase सहाय्यकाशी चॅट करा",
      launcherText: "AgriEase ला विचारा",
      responseFailed: "उत्तर मिळाले नाही. कृपया पुन्हा प्रयत्न करा.",
      responseFallback: "माफ करा, सध्या उत्तर देण्यात अडचण येत आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
    },
    messages: {
      cartEmpty: "तुमचा कार्ट रिकामा आहे",
      requiredFields: "कृपया सर्व आवश्यक माहिती भरा",
      selectImage: "कृपया पानाचा फोटो अपलोड करा",
      predictionFailed: "भाकीत अयशस्वी. बॅकएंड प्रतिसाद देत नाही.",
      loadOrdersError: "ऑर्डर्स लोड करण्यात अयशस्वी",
      updateStatusError: "स्थिती अपडेट करता आली नाही",
      sessionExpired: "सेशन संपले. कृपया लॉगआउट करून पुन्हा लॉगिन करा.",
      paymentEnterTxn: "कृपया व्यवहार क्रमांक भरा",
      paymentTxnLength: "Transaction ID किमान 12 अक्षरांचा हवा",
      paymentConfirmError: "पेमेंट निश्चित करण्यात अयशस्वी. पुन्हा प्रयत्न करा.",
      paymentConfirmed: "पेमेंट निश्चित! पुरवठादार पुष्टीची प्रतीक्षा.",
      imageTooLarge: "प्रतिमेचा आकार 2MB पेक्षा कमी असावा",
      imageType: "कृपया इमेज फाइल निवडा",
      imageReadError: "प्रतिमा वाचताना त्रुटी आली",
      profileUpdated: "प्रोफाइल यशस्वीरीत्या अपडेट केले!",
      profileUpdateError: "प्रोफाइल अपडेट करता आले नाही",
      passwordMismatch: "नवीन पासवर्ड जुळत नाहीत",
      passwordLength: "पासवर्ड किमान 6 अक्षरांचा असणे आवश्यक आहे",
      passwordChanged: "पासवर्ड यशस्वीरीत्या बदलला!",
      selectRentalDates: "कृपया भाड्याच्या तारखा निवडा",
      endDateInvalid: "शेवटची तारीख सुरुवातीच्या तारखेनंतरची असावी",
      equipmentReserved: "उपकरण कार्टमध्ये राखीव केले",
      loadEquipmentError: "उपकरणे लोड करता आली नाहीत. पुन्हा प्रयत्न करा.",
      loadProductsError: "उत्पादने लोड करण्यात अयशस्वी",
      authFailed: "प्रमाणीकरण अयशस्वी. कृपया पुन्हा लॉगिन करा.",
      clearCompletedNone: "काढण्यासाठी पूर्ण झालेल्या ऑर्डर्स नाहीत",
      clearCompletedError: "संपलेल्या ऑर्डर्स काढता आल्या नाहीत",
      unableSync: "सर्व्हरशी सिंक होत नाही. शेवटचा जतन केलेला डेटा दाखवत आहोत.",
      uploadingImage: "प्रतिमा अपलोड करत आहे...",
      roleSwitchFailed: "प्रोफाइल बदलता आले नाही. पुन्हा प्रयत्न करा.",
    },
    orderTracking: {
      loadError: "ट्रॅकिंग तपशील लोड करता आले नाहीत",
      loading: "ट्रॅकिंग तपशील लोड होत आहेत...",
      noData: "कोणतीही ट्रॅकिंग माहिती उपलब्ध नाही.",
      title: "ऑर्डर ट्रॅकिंग",
      currentStatus: "सध्याची स्थिती",
      deliveryProgress: "डिलिव्हरी प्रगती",
      timeline: "टाइमलाइन",
      location: "स्थान",
      viewProof: "डिलिव्हरी पुरावा पहा",
      statusLabels: {
        pending: "ऑर्डर ठेवली",
        confirmed: "पुरवठादाराने निश्चित केली",
        assigned: "प्रतिनिधी नियुक्त",
        pickedUp: "उचलली",
        outForDelivery: "डिलिव्हरीसाठी मार्गावर",
        delivered: "वितरित",
      },
    },
    status: {
      pending: "प्रलंबित",
      confirmed: "निश्चित",
      delivered: "वितरित",
      cancelled: "रद्द",
      healthy: "आरोग्यपूर्ण",
      monitor: "नजर ठेवा",
      attention: "काळजी",
    },
    farmer: {
      checkout: {
        title: "चेकआउट",
        subtitle: "आपली ऑर्डर पूर्ण करा",
        alertText: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत तुमची ऑर्डर PENDING राहील.",
        confirmTitle: "आपली ऑर्डर निश्चित करायची?",
        confirmItems: "वस्तू",
        confirmTotal: "एकूण रक्कम",
        confirmPayment: "पेमेंट पद्धत",
        confirmDelivery: "वितरण पत्ता",
        confirmCta: "ऑर्डर करण्यासाठी OK क्लिक करा",
        upiOption: "UPI QR कोड",
        codOption: "डिलिव्हरीवर रोख",
        emptyTitle: "तुमचा कार्ट रिकामा आहे",
        emptyAction: "खरेदी सुरू ठेवा",
        toastSuccess: "ऑर्डर तयार झाली. पुरवठादाराच्या पुष्टीची प्रतीक्षा.",
        toastError: "ऑर्डर करता आली नाही",
        toastOutdatedCartItems: "कार्टमधील काही वस्तू कालबाह्य झाल्या आहेत. कृपया कार्ट रिकामे करून पुन्हा वस्तू जोडा.",
        toastMixedSuppliers: "तुमच्या कार्टमध्ये अनेक पुरवठादारांच्या वस्तू आहेत. कृपया वेगळ्या ऑर्डर्स करा.",
      },
      crops: {
        title: "पिके खरेदी करा",
        subtitle: "पुरवठादारांनी निवडलेले ताजे इनपुट.",
        empty: "कोणतीही पिके उपलब्ध नाहीत",
      },
      market: {
        title: "मार्केटप्लेस",
        subtitle: "काही मिनिटांत पुरवठा जोडा आणि ऑर्डर करा.",
        empty: "कोणतीही उत्पादने उपलब्ध नाहीत",
        categories: "श्रेण्या",
        all: "सर्व",
        sortBy: "क्रमवारी",
        other: "इतर",
        sort: {
          default: "मूळ",
          nameAsc: "नाव A-Z",
          priceLowHigh: "किंमत: कमी ते जास्त",
          priceHighLow: "किंमत: जास्त ते कमी",
        },
      },
      home: {
        loading: "शेतकरी डॅशबोर्ड लोड होत आहे",
        heroKicker: "शेती संचालन",
        heroSubtitle: "एका स्क्रीनवर शेत, उपकरणे आणि मार्केट क्रियाकलाप सांभाळा.",
        heroGreetingPrefix: "पुन्हा स्वागत आहे",
        heroChipOverview: "शेत आढावा",
        heroChipCropsTracked: "पिके ट्रॅक केली",
        heroChipOrdersInFlow: "मार्केट ऑर्डर्स प्रवाहात",
        openCropAdvisor: "पीक सल्लागार उघडा",
        shortcutsTitle: "शेतकरी शॉर्टकट",
        liveActivityKicker: "थेट क्रियाकलाप",
        fieldPulseTitle: "शेत नाडी",
        detailsKicker: "आढावा",
        farmDetailsTitle: "शेत तपशील",
        refresh: "डेटा रीफ्रेश करा",
        addFarmSize: "प्रोफाइलमध्ये जोडा",
        defaultCrops: {
          rice: "तांदूळ",
          wheat: "गहू",
        },
        activity: {
          active: "सक्रिय",
          running: "चालू",
          ordersMoving: "मार्केट विनंत्या चेकआउटमधून पुढे जात आहेत.",
          noActiveOrders: "सध्या कोणत्याही सक्रिय मार्केट ऑर्डर्स नाहीत.",
          equipmentInProgress: "उपकरण बुकिंग अजून सुरू आहे.",
          rentalClear: "आजचे भाडे वेळापत्रक मोकळे आहे.",
          cropStable: "या आठवड्यात पिकांची स्थिती स्थिर दिसते.",
          cropMonitor: "काही पिकांवर लक्ष ठेवण्याची गरज आहे.",
        },
        stat: {
          farmSize: { label: "शेतीचा आकार", helper: "तुमची लागवड केलेली जमीन" },
          avgHealth: { label: "सरासरी आरोग्य", helper: "पीक जोम" },
          marketOrders: { label: "मार्केट ऑर्डर्स", helper: "या हंगामात दिल्या" },
          rentals: { label: "सक्रिय भाडे", helper: "शेतातील उपकरणे" },
        },
        quick: {
          market: { title: "मार्केट पहा", subtitle: "बियाणे, इनपुट्स आणि पुरवठा" },
          tools: { title: "उपकरणे भाड्याने घ्या", subtitle: "विश्वासार्ह मशीन बुक करा" },
          disease: { title: "रोग निदान", subtitle: "एआय पीक स्कॅन" },
          orders: { title: "माझ्या ऑर्डर्स", subtitle: "डिलिव्हरी ट्रॅक करा" },
        },
        cropsSection: {
          kicker: "पीक आरोग्य सारांश",
          title: "आपली शेतं पाहा",
          cta: "सर्व पहा →",
          acres: "एकर",
          statuses: {
            healthy: "आरोग्यपूर्ण",
            monitor: "नजर ठेवा",
            attention: "काळजी",
          },
        },
      },
      disease: {
        title: "वनस्पती रोग निदान",
        subtitle: "रोग ओळखण्यासाठी पानाचा फोटो अपलोड करा.",
        uploadLabel: "पानाचा फोटो अपलोड करा",
        button: "रोग शोधा",
        description: "वर्णन",
        prevention: "प्रतिबंध",
        confidence: "विश्वास पातळी",
        buyLink: "शिफारस केलेले पूरक खरेदी करा",
      },
      orders: {
        title: "माझ्या ऑर्डर्स",
        subtitle: "आपल्या ऑर्डर आणि बुकिंग इतिहासावर नजर ठेवा",
        empty: "अद्याप कोणतीही ऑर्डर नाही. खरेदी सुरू करा!",
        toastCancelled: "ऑर्डर यशस्वीरीत्या रद्द केली",
        cancelling: "रद्द करत आहे...",
        status: {
          pendingPaid: "पुरवठादार पुष्टीची प्रतीक्षा",
          pendingUnpaid: "पेमेंट व पुष्टी प्रलंबित",
          confirmed: "पुरवठादाराने निश्चित केली - तयारीत",
          delivered: "वितरित",
          cancelled: "रद्द",
        },
      },
      payment: {
        title: "पेमेंट पूर्ण करा",
        subtitle: "UPI द्वारे पैसे भरण्यासाठी QR कोड स्कॅन करा",
        amountToPay: "देय रक्कम",
        upiPayment: "UPI पेमेंट",
        completeWithin: "पेमेंट पूर्ण करा",
        scanQrPrompt: "कोणत्याही UPI अॅपने QR स्कॅन करा",
        payTo: "यांना पेमेंट करा",
        supportedApps: "PhonePe • GPay • Paytm • BHIM",
        verifying: "पेमेंट पडताळत आहे...",
        securityNote: "तुमचे पेमेंट 256-बिट SSL एन्क्रिप्शनने सुरक्षित आहे",
        note: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत ऑर्डर PENDING राहील.",
        instructionsTitle: "पेमेंट सूचना:",
        steps: {
          one: "कोणतीही UPI अॅप (GPay, PhonePe, Paytm, BHIM इ.) उघडा",
          two: '"Scan QR" टॅप करा आणि वरील QR कोड स्कॅन करा',
          three: "रक्कम तपासा:",
          four: "तुमच्या UPI PIN ने पेमेंट पूर्ण करा",
          five: "अॅपमधील 12 अंकी Transaction/UTR ID कॉपी करा",
          six: 'Transaction ID खाली भरा आणि "Confirm Payment" क्लिक करा',
        },
        amountPrefix: "INR",
        button: "पेमेंट निश्चित करा",
        back: "कार्टकडे परत",
      },
      profile: {
        title: "माझे प्रोफाइल",
        subtitle: "आपली खाते माहिती सांभाळा",
        role: "शेतकरी",
        deleteConfirm: "तुमचे खाते कायमचे हटवायचे का? यामुळे प्रोफाइल आणि संबंधित डेटा काढला जाईल. ही कृती मागे घेता येणार नाही.",
        avatarHint: 'फोटो बदलण्यासाठी "प्रोफाइल संपादित करा" क्लिक करा',
        changePhoto: "फोटो बदला",
        removePhoto: "काढा",
        statsError: "स्टॅट्स सिंक होत नाहीत. शेवटचे मूल्य दाखवत आहोत.",
        accountStatsTitle: "खाते आकडेवारी",
        stats: {
          totalOrders: "मार्केट ऑर्डर्स",
          equipmentBookings: "उपकरण बुकिंग",
          activeBookings: "सक्रिय भाडे",
          diseaseScans: "रोग स्कॅन",
          activeNow: "सध्या सक्रिय",
        },
        placeholders: {
          phone: "फोन क्रमांक भरा",
          address: "तुमचा पत्ता भरा",
          farmSize: "उदा. 5 एकर",
          cropTypes: "उदा. भात, गहू, भाजीपाला",
        },
        form: {
          farmSizeLabel: "शेतीचा आकार (एकरमध्ये)",
          cropTypesLabel: "पीक प्रकार",
        },
      },
      account: {
        title: "माझे प्रोफाइल",
        subtitle: "आपली खाते माहिती सांभाळा",
        role: "शेतकरी",
      },
      tools: {
        title: "साधने भाड्याने घ्या",
        subtitle: "लवचिक तारखांसह उपकरणे आरक्षित करा.",
        loading: "उपकरणे लोड होत आहेत...",
        empty: "कोणतीही साधने उपलब्ध नाहीत",
        available: "उपलब्ध",
        unavailable: "उपलब्ध नाही",
      },
      cropAdvisor: {
        title: "एआय पीक सल्लागार",
        subtitle: "हवामानावर आधारित पीक योग्यता टक्केवारी शिफारसी.",
        findCrops: "तुमच्या हवामानासाठी पिके शोधा",
        enterLocation: "गाव किंवा शहर भरा",
        useCurrentLocation: "सध्याचे स्थान वापरा",
        locating: "स्थान शोधत आहे...",
        generate: "तयार करा",
        analyzing: "विश्लेषण करत आहे...",
        result: "निकाल",
        humidity: "आर्द्रता",
        generateAiAdvisory: "एआय सल्ला तयार करा",
        generatingAiAdvice: "एआय सल्ला तयार करत आहे...",
        suitability: "योग्यता",
        recentRecommendations: "अलीकडील शिफारसी",
        noHistory: "अद्याप कोणत्याही शिफारसी नाहीत.",
        toastSuccess: "पीक शिफारसी तयार झाल्या",
        toastError: "शिफारस तयार करता आली नाही",
        toastAiError: "एआय सल्ला तयार करता आला नाही",
        toastEnterLocation: "कृपया स्थान भरा",
        toastLocationSelected: "सध्याचे स्थान निवडले",
        toastLocationError: "स्थान मिळवता आले नाही",
        networkLocation: "नेटवर्क स्थान वापरत आहे (IP आधारित)",
      },
      landMeasurement: {
        title: "लाइव्ह GPS जमीन मोजणी",
        subtitle: "नकाशावर सीमा बिंदू चिन्हांकित करा आणि एकरमध्ये क्षेत्रफळ मोजा.",
        optionalLabel: "पर्यायी लेबल (उदा., पश्चिम शेत)",
        useCurrentLocation: "सध्याचे स्थान वापरा",
        locating: "स्थान शोधत आहे...",
        addCurrentPoint: "सध्याचा बिंदू जोडा",
        clear: "साफ करा",
        saveMeasurement: "मोजणी जतन करा",
        saving: "जतन करत आहे...",
        street: "रस्ता",
        satellite: "उपग्रह",
        points: "बिंदू",
        area: "क्षेत्रफळ",
        acres: "एकर",
        recentMeasurements: "अलीकडील मोजणी",
        noMeasurements: "जतन केलेली मोजणी नाही.",
        unnamedField: "नाव नसलेले शेत",
        toastMinPoints: "कृपया किमान 4 बिंदू चिन्हांकित करा",
        toastSaved: "जमीन मोजणी जतन झाली",
        toastSaveError: "जमीन मोजणी जतन करता आली नाही",
        toastCentered: "नकाशा सध्याच्या स्थानावर केंद्रित केला",
        toastPointAdded: "सध्याचे स्थान बिंदू म्हणून जोडले",
        toastNetworkPoint: "नेटवर्क स्थान बिंदू म्हणून जोडले",
        toastLocationError: "स्थान मिळवता आले नाही",
        networkLocation: "नेटवर्क स्थान वापरत आहे (IP आधारित)",
      },
      weeklySchedule: {
        title: "एआय साप्ताहिक पीक वेळापत्रक",
        subtitle: "सेंद्रिय किंवा असेंद्रिय साप्ताहिक शेती योजना तयार करा आणि PDF मध्ये निर्यात करा.",
        crop: "पीक",
        planType: "योजना प्रकार",
        organic: "सेंद्रिय",
        inorganic: "असेंद्रिय",
        totalWeeks: "एकूण आठवडे",
        landArea: "जमीन क्षेत्र (एकर)",
        generatePlan: "साप्ताहिक योजना तयार करा",
        generating: "तयार करत आहे...",
        generateAiSummary: "एआय सारांश तयार करा",
        generatingAiSummary: "एआय सारांश तयार करत आहे...",
        exportPdf: "PDF निर्यात करा",
        plan: "योजना",
        week: "आठवडा",
        savedHistory: "जतन केलेला वेळापत्रक इतिहास",
        noSchedules: "अद्याप कोणतेही वेळापत्रक तयार केले नाही.",
        weeks: "आठवडे",
        toastSuccess: "साप्ताहिक वेळापत्रक तयार झाले",
        toastError: "वेळापत्रक तयार करता आले नाही",
        toastAiError: "एआय सारांश तयार करता आला नाही",
        pdfTitle: "AgriEase साप्ताहिक योजना",
        pdfType: "प्रकार",
        pdfArea: "क्षेत्र",
      },
    },
    supplier: {
      home: {
        loading: "पुरवठादार डॅशबोर्ड लोड होत आहे",
        kicker: "पुरवठादार संचालन",
        heroSubtitle: "लाईव्ह ऑर्डर्स ट्रॅक करा, लिस्टिंग अपडेट ठेवा आणि डिस्पॅच कार्यक्षमता सहज पाहा.",
        heroChips: {
          productsLive: "उत्पादने लाईव्ह",
          equipmentItems: "उपकरणे",
          pendingApprovals: "प्रलंबित मंजुरी",
        },
        openOrderCenter: "ऑर्डर केंद्र उघडा",
        actionsKicker: "क्रिया",
        shortcutsTitle: "पुरवठादार शॉर्टकट",
        pipelineKicker: "ऑर्डर पाइपलाइन",
        pipelineTitle: "नवीन शेतकरी विनंत्या",
        noOrdersYet: "अजून ऑर्डर्स नाहीत. सुरुवातीसाठी तुमच्या लिस्टिंगचा प्रचार करा.",
        and: "आणि",
        commercialKicker: "व्यावसायिक आढावा",
        commercialTitle: "महसूल आणि ऑर्डर गती",
        inventoryKicker: "साठा झलक",
        inventoryTitle: "पुरवठा तयार ठेवा",
        updateCatalog: "कॅटलॉग अपडेट करा",
        detailsKicker: "तपशील",
        businessOverview: "व्यवसाय आढावा",
        openProfile: "प्रोफाइल उघडा",
        stats: {
          productsLive: "लाईव्ह उत्पादने",
          crops: "पिके",
          and: "आणि",
          supplies: "साठा",
          equipmentFleet: "उपकरण फ्लीट",
          availableToday: "आज उपलब्ध",
          pendingOrders: "प्रलंबित ऑर्डर्स",
          fulfillmentRate: "पूर्णता दर",
          revenueMonth: "महिना महसूल",
          totalOrders: "एकूण ऑर्डर्स",
        },
        quick: {
          manageProducts: { title: "उत्पादने व्यवस्थापित करा", subtitle: "पिके आणि कृषी इनपुट सूचीबद्ध करा" },
          manageEquipment: { title: "उपकरणे व्यवस्थापित करा", subtitle: "ट्रॅक्टर आणि साधने भाड्याने द्या" },
          reviewOrders: { title: "ऑर्डर्स पुनरावलोकन", subtitle: "निश्चित करा आणि पाठवा" },
          editProfile: { title: "प्रोफाइल संपादित करा", subtitle: "व्यवसाय माहिती अपडेट करा" },
        },
        inventory: {
          topProducts: "शीर्ष उत्पादने",
          addBestSellers: "तुमची सर्वोत्तम विक्री जोडा",
          skusListed: "SKU सूचीबद्ध",
          equipmentRates: "उपकरण दर",
          avgPerDay: "सरासरी/दिवस",
          noEquipment: "अजून उपकरणे जोडलेली नाहीत",
          avgOrderValue: "सरासरी ऑर्डर मूल्य",
          fulfilledOrders: "पूर्ण ऑर्डर्स",
        },
        spotlight: {
          catalogCoverage: "लाईव्ह कॅटलॉग कव्हरेज",
          activeListings: "सक्रिय लिस्टिंग",
          cropFocusedAvailable: "पीक-केंद्रित उत्पादने शेतकऱ्यांसाठी उपलब्ध आहेत.",
          addCropProducts: "कॅटलॉग वाढवण्यासाठी पीक उत्पादने जोडा.",
          equipmentReadiness: "उपकरण तयारी",
          ready: "तयार",
          fleetRealtime: "फ्लीट उपलब्धता शेतकऱ्यांना तत्काळ दिसते.",
          addRentalEquipment: "बुकिंग मागणीसाठी भाड्याची उपकरणे जोडा.",
          orderFulfillment: "ऑर्डर पूर्णता",
          ordersNeedAction: "ऑर्डर्सना अजून कृती हवी आहे.",
          allOnPace: "ट्रॅक केलेल्या सर्व ऑर्डर्स सध्या योग्य गतीत आहेत.",
        },
        business: {
          totalRevenue: "एकूण महसूल",
          monthRevenue: "महिना महसूल",
          avgOrderTicket: "सरासरी ऑर्डर मूल्य",
          fulfillmentRate: "पूर्णता दर",
        },
      },
      products: {
        title: "उत्पादने व्यवस्थापित करा",
        subtitle: "तुमची उत्पादन लिस्टिंग जोडा आणि व्यवस्थापित करा",
        catalogTitle: "उत्पादन कॅटलॉग",
        catalogSubtitle: "पुरवठादार साठा अद्ययावत ठेवा",
        empty: "अजून उत्पादने नाहीत. सुरुवातीसाठी \"उत्पादन जोडा\" क्लिक करा!",
        noDescription: "वर्णन नाही",
        confirm: {
          delete: "हे उत्पादन हटवायचे आहे का?",
        },
        toast: {
          added: "उत्पादन यशस्वीरीत्या जोडले!",
          updated: "उत्पादन यशस्वीरीत्या अपडेट झाले!",
          deleted: "उत्पादन यशस्वीरीत्या हटवले!",
          saveError: "उत्पादन जतन करता आले नाही",
          deleteError: "उत्पादन हटवता आले नाही",
        },
        form: {
          addTitle: "नवीन उत्पादन जोडा",
          editTitle: "उत्पादन संपादित करा",
          productName: "उत्पादन नाव",
          productNamePlaceholder: "उदा., सेंद्रिय खत",
          descriptionPlaceholder: "उत्पादनाचे वर्णन",
          price: "किंमत",
          type: "प्रकार",
          image: "उत्पादन प्रतिमा",
        },
        types: {
          cropSeeds: "पीक/बियाणे",
          fertilizer: "खत",
          pesticide: "कीटकनाशक",
        },
      },
      equipment: {
        title: "उपकरणे व्यवस्थापित करा",
        subtitle: "भाड्यासाठी उपकरणे जोडा आणि व्यवस्थापित करा",
        fleetTitle: "उपकरण फ्लीट",
        fleetSubtitle: "भाडे वस्तूंची उपलब्धता आणि दर ट्रॅक करा",
        empty: "अजून उपकरणे नाहीत. सुरुवातीसाठी \"उपकरण जोडा\" क्लिक करा!",
        noDescription: "वर्णन नाही",
        confirm: {
          delete: "हे उपकरण हटवायचे आहे का?",
        },
        toast: {
          added: "उपकरण यशस्वीरीत्या जोडले!",
          updated: "उपकरण यशस्वीरीत्या अपडेट झाले!",
          deleted: "उपकरण यशस्वीरीत्या हटवले!",
          saveError: "उपकरण जतन करता आले नाही",
          deleteError: "उपकरण हटवता आले नाही",
          notFound: "उपकरण सापडले नाही",
          availabilityUpdated: "उपलब्धता अपडेट झाली!",
          availabilityError: "उपलब्धता अपडेट करता आली नाही",
        },
        form: {
          addTitle: "नवीन उपकरण जोडा",
          editTitle: "उपकरण संपादित करा",
          name: "उपकरण नाव",
          namePlaceholder: "उदा., ट्रॅक्टर",
          descriptionPlaceholder: "उपकरणाचे वर्णन",
          dailyRate: "दैनिक दर",
          image: "उपकरण प्रतिमा",
          availableForRent: "भाड्यासाठी उपलब्ध",
        },
      },
      orders: {
        title: "आगत ऑर्डर्स",
        subtitle: "शेतकरी ऑर्डर्स, नियुक्त्या आणि वितरण प्रगती व्यवस्थापित करा",
        controlCenter: "ऑर्डर नियंत्रण केंद्र",
        controlSubtitle: "ऑर्डर पाइपलाइन फिल्टर, सॉर्ट आणि कृती करा",
        allStatuses: "सर्व स्थिती",
        allPayments: "सर्व पेमेंट्स",
        noOrders: "अजून ऑर्डर्स नाहीत.",
        noOrdersForFilter: "तुमच्या फिल्टर्सशी जुळणाऱ्या ऑर्डर्स नाहीत.",
        assignedAgent: "नियुक्त वितरण प्रतिनिधी",
        notAssigned: "नियुक्त नाही",
        rejectionReason: "नकाराचे कारण",
        noRejectionReason: "प्रतिनिधीकडून कारण दिलेले नाही.",
        confirmOrder: "ऑर्डर निश्चित करा",
        selectDeliveryAgent: "वितरण प्रतिनिधी निवडा",
        selectDeliveryAgentFirst: "प्रथम वितरण प्रतिनिधी निवडा",
        assignAgent: "प्रतिनिधी नियुक्त करा",
        reassignAgent: "प्रतिनिधी पुन्हा नियुक्त करा",
        sort: {
          newestFirst: "नवीन प्रथम",
          oldestFirst: "जुनी प्रथम",
          highestAmount: "सर्वाधिक रक्कम",
          lowestAmount: "कमी रक्कम",
        },
        toast: {
          confirmedAndAssigned: "ऑर्डर निश्चित झाली आणि वितरण प्रतिनिधी नियुक्त झाला",
          statusUpdated: "ऑर्डर स्थिती अपडेट झाली",
          removedFromHistory: "ऑर्डर इतिहासातून काढली",
          removeError: "ऑर्डर काढता आली नाही",
          agentAssigned: "वितरण प्रतिनिधी यशस्वीरीत्या नियुक्त झाला",
          assignError: "प्रतिनिधी नियुक्त करता आला नाही",
          removedSome: "काही पूर्ण ऑर्डर्स इतिहासातून काढल्या",
          failedSome: "काही पूर्ण ऑर्डर्स काढता आल्या नाहीत",
        },
      },
      profile: {
        title: "माझे प्रोफाइल",
        subtitle: "तुमचे व्यवसाय खाते व्यवस्थापित करा आणि आकडेवारी पहा",
        accountSubtitle: "प्रोफाइल, सुरक्षा आणि खाते तपशील अपडेट करा",
        personalInfo: "वैयक्तिक माहिती",
        businessDetails: "व्यवसाय तपशील",
        businessStatistics: "व्यवसाय आकडेवारी",
        phonePlaceholder: "फोन क्रमांक भरा",
        addressPlaceholder: "तुमचा व्यवसाय पत्ता भरा",
        descriptionPlaceholder: "तुमचा व्यवसाय आणि उत्पादने वर्णन करा",
        businessNamePlaceholder: "उदा., ABC Agri Supplies",
        selectBusinessType: "व्यवसाय प्रकार निवडा",
        updatePassword: "पासवर्ड अपडेट करा",
        changePasswordFailed: "पासवर्ड बदलता आला नाही",
        changePhoto: "फोटो बदला",
        removePhoto: "काढा",
        deleteAccount: "खाते हटवा",
        statsError: "लाईव्ह आकडेवारी सध्या लोड होत नाही",
        accountDeleted: "खाते यशस्वीरीत्या हटवले",
        deleteAccountFailed: "खाते हटवता आले नाही",
        loadProfileFailed: "प्रोफाइल लोड करता आले नाही",
        stats: {
          productsListed: "सूचीबद्ध उत्पादने",
          equipmentListed: "सूचीबद्ध उपकरणे",
          totalSales: "एकूण विक्री",
          totalOrders: "एकूण ऑर्डर्स",
        },
        businessTypes: {
          equipmentRental: "उपकरणे भाडे",
          seedsAndFertilizers: "बियाणे आणि खते",
          pesticides: "कीटकनाशके",
          generalSupplies: "सामान्य पुरवठा",
          other: "इतर",
        },
      },
    },
    agent: {
      dashboard: {
        deliveryAgent: "वितरण प्रतिनिधी",
        notProvided: "उपलब्ध नाही",
        localServiceArea: "स्थानिक सेवा क्षेत्र",
        defaultVehicleName: "अॅग्री व्हॅन",
        defaultSupplierName: "AgriEase पुरवठादार",
        defaultProductName: "शेती उत्पादन",
        workspace: "वितरण संचालन कार्यक्षेत्र",
        portal: "वितरण प्रतिनिधी पोर्टल",
        kicker: "वितरण संचालन",
        title: "वितरण प्रतिनिधी डॅशबोर्ड",
        subtitle: "AgriEase लॉजिस्टिक्स नियंत्रण पॅनेल",
        assigned: "नियुक्त",
        inTransit: "मार्गात",
        completed: "पूर्ण",
        refreshOrders: "ऑर्डर्स रीफ्रेश करा",
        closeEdit: "संपादन बंद करा",
        lastUpdated: "शेवटचे अद्यतन",
        loadOrdersFailed: "नियुक्त ऑर्डर्स लोड करण्यात अयशस्वी",
        profileDeleted: "प्रोफाइल यशस्वीरीत्या हटवले",
        deleteProfileFailed: "प्रोफाइल हटवता आले नाही",
        orderUpdated: "ऑर्डर अपडेट झाली",
        chooseImageFirst: "प्रथम प्रतिमा निवडा",
        proofUploaded: "डिलिव्हरी पुरावा अपलोड झाला",
        proofUploadFailed: "डिलिव्हरी पुरावा अपलोड अयशस्वी",
        paymentCollected: "COD पेमेंट यशस्वीरीत्या संकलित झाले",
        collectPaymentFailed: "पेमेंट संकलित करता आले नाही",
        loadingDashboard: "डिलिव्हरी डॅशबोर्ड लोड होत आहे",
        deleteConfirm: "तुमचे खाते कायमचे हटवायचे का? ही कृती मागे घेता येणार नाही.",
        rejectPrompt: "पर्यायी: ही ऑर्डर नाकारण्याचे कारण द्या (पुरवठादाराला दिसेल).",
        orderRejected: "ऑर्डर नाकारली",
        supplierLocationFallback: "पुरवठादाराचे स्थान",
        farmerLocationFallback: "शेतकऱ्याचे स्थान",
        routeOverview: "मार्ग आढावा",
        liveRouteMap: "लाईव्ह मार्ग नकाशा",
        tracking: "ट्रॅकिंग",
        selectOrderForMap: "पुरवठादार आणि शेतकरी नकाशा पाहण्यासाठी ऑर्डर निवडा.",
        mapTitle: "डिलिव्हरी मार्ग नकाशा",
        agentSnapshot: "प्रतिनिधी झलक",
        vehicle: "वाहन",
        vehicleNo: "वाहन क्रमांक",
        serviceArea: "सेवा क्षेत्र",
        rating: "रेटिंग",
        operationsPulse: "संचालन स्थिती",
        incomingRequests: "आगत विनंत्या",
        acceptedOrders: "स्वीकृत ऑर्डर्स",
        selectedOrder: "निवडलेली ऑर्डर",
        none: "काही नाही",
        paymentTracking: "पेमेंट ट्रॅकिंग",
        codFollowUps: "COD फॉलो-अप",
        completedDeliveries: "पूर्ण डिलिव्हरी",
        assignedOrders: "नियुक्त ऑर्डर्स",
        pendingRequests: "प्रलंबित विनंत्या",
        inTransitOrders: "मार्गातील ऑर्डर्स",
        deliveredToday: "आज वितरित",
        dispatchAnalytics: "डिस्पॅच विश्लेषण",
        dailyDeliveryLoad: "दैनंदिन डिलिव्हरी भार",
        liveStats: "लाईव्ह आकडे",
        deliveryStatusDetails: "डिलिव्हरी स्थिती तपशील",
        selectOrderForProgress: "प्रगती पाहण्यासाठी ऑर्डर निवडा.",
        trackingOrder: "ट्रॅक करत आहे ऑर्डर",
        for: "साठी",
        moveToNextStage: "पुढील टप्प्यावर जा",
        uploadDeliveryPhoto: "डिलिव्हरी फोटो अपलोड करा",
        codOrder: "COD ऑर्डर",
        markPaymentCollected: "पेमेंट संकलित झाले म्हणून चिन्हांकित करा",
        paymentCollectedLabel: "पेमेंट संकलित झाले",
        profileTitle: "वितरण प्रतिनिधी प्रोफाइल",
        incomingRequestsTitle: "आगत डिलिव्हरी विनंत्या",
        noIncomingRequests: "कोणतीही आगत विनंती नाही.",
        noAcceptedOrders: "अजून कोणतीही स्वीकृत ऑर्डर नाही.",
        navigation: "नेव्हिगेशन",
        collectPayment: "पेमेंट गोळा करा",
        collect: "गोळा करा",
        paid: "पेमेंट झाले",
        pending: "प्रलंबित",
        codBadge: "COD",
        upiBadge: "UPI",
        actionPickedUp: "उचलले",
        actionOutForDelivery: "डिलिव्हरीसाठी बाहेर",
        actionDelivered: "वितरित",
        deliveryHistory: "डिलिव्हरी इतिहास",
        deliveryDate: "डिलिव्हरी तारीख",
        deliveryProof: "डिलिव्हरी पुरावा",
        viewProof: "पुरावा पहा",
        noProofUploaded: "पुरावा अपलोड नाही",
        noHistory: "अजून डिलिव्हरी इतिहास नाही.",
        loadingAssignedOrders: "नियुक्त ऑर्डर्स लोड होत आहेत...",
        noAssignedOrders: "कोणतीही नियुक्त ऑर्डर सापडली नाही.",
        footerLine1: "स्मार्ट डिलिव्हरी संचालन.",
        footerLine2: "पुरवठादार डिस्पॅच आणि शेतकरी डिलिव्हरी समन्वयित ठेवत आहोत.",
        chart: {
          assigned: "नियुक्त",
          pending: "प्रलंबित",
          transit: "मार्गात",
          delivered: "वितरित",
        },
        table: {
          supplierName: "पुरवठादार नाव",
          farmerName: "शेतकरी नाव",
          product: "उत्पादन",
          deliveryAddress: "डिलिव्हरी पत्ता",
          accept: "स्वीकारा",
          reject: "नकारा",
          viewDetails: "तपशील पहा",
          updateStatus: "स्थिती अपडेट",
          navigation: "नेव्हिगेशन",
        },
      },
    },
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const AVAILABLE_LANGUAGES = [
  { code: "en", label: "English" },
  { code: "mr", label: "मराठी" },
];

function resolveTranslation(dictionary, key) {
  return key.split(".").reduce((acc, part) => (acc ? acc[part] : undefined), dictionary);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") {
      return "en";
    }
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored && translations[stored]) {
      return stored;
    }
    return window.navigator?.language?.toLowerCase().startsWith("mr") ? "mr" : "en";
  });

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const value = useMemo(() => {
    const translate = (key) => {
      const localized = resolveTranslation(translations[language], key);
      if (localized) {
        return localized;
      }
      return resolveTranslation(translations.en, key) ?? key;
    };

    return {
      language,
      setLanguage,
      t: translate,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
