import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "agriease-language";

const translations = {
  en: {
    common: {
      brandName: "AgriEase",
      brandAlt: "AgriEase - Growing Smarter",
      login: "Login",
      register: "Register",
      joinFarmer: "Join as Farmer",
      joinSupplier: "Join as Supplier",
      alreadyAccount: "Already have an account",
      alreadyMember: "Already a member? Login",
      createAccount: "Create Account",
      createFreeAccount: "Create Free Account",
      language: "Language",
      farmer: "Farmer",
      supplier: "Supplier",
      logout: "Logout",
      actions: {
        browseMarket: "Browse Market",
        checkout: "Checkout",
        clearCart: "Clear Cart",
        addToCart: "Add to Cart",
        remove: "Remove",
        continueShopping: "Continue Shopping",
        refresh: "Refresh data",
        viewAll: "View all →",
        editProfile: "Edit Profile",
        saveChanges: "Save Changes",
        cancel: "Cancel",
        cancelOrder: "Cancel Order",
        confirm: "Confirm",
        markDelivered: "Mark Delivered",
        removeHistory: "Remove from History",
        clearFilters: "Clear Filters",
        clearCompleted: "Clear All Completed",
        showActive: "Show Active Only",
        activeOnly: "✓ Active Orders Only",
        placeOrder: "Place Order",
        processing: "Processing...",
        detectDisease: "Detect Disease",
        confirmPayment: "Confirm Payment",
        paymentConfirmed: "Payment Confirmed",
        backToCart: "Back to Cart",
        addProduct: "+ Add Product",
        addEquipment: "+ Add Equipment",
        updateProduct: "Update Product",
        updateEquipment: "Update Equipment",
        delete: "Delete",
        edit: "Edit",
        markAvailable: "Mark Available",
        markUnavailable: "Mark Unavailable",
        switchProfile: "Switch profile",
        switchToFarmer: "Switch to Farmer dashboard",
        switchToSupplier: "Switch to Supplier dashboard",
      },
      labels: {
        shoppingCart: "Shopping Cart",
        cartSubtitle: "Review and manage your items before checkout",
        cartEmpty: "Your cart is empty",
        product: "Product",
        crop: "Crop",
        equipmentRental: "Equipment Rental",
        rate: "Rate",
        duration: "Duration",
        dates: "Dates",
        orderSummary: "Order Summary",
        totalItems: "Total Items",
        total: "Total",
        paymentMethod: "Payment Method",
        shippingDetails: "Shipping Details",
        fullName: "Full Name",
        email: "Email",
        phoneNumber: "Phone Number",
        address: "Address",
        city: "City",
        state: "State",
        pincode: "Pincode",
        qty: "Qty",
        important: "Important",
        pendingNote: "After payment, your order stays PENDING until supplier confirmation.",
        items: "Items",
        customerDetails: "Customer Details",
        shippingAddress: "Shipping Address",
        orderDate: "Order Date",
        status: "Status",
        paymentStatus: "Payment Status",
        available: "Available",
        unavailable: "Not Available",
        lastSynced: "Last synced",
        description: "Description",
        prevention: "Prevention",
        confidence: "Confidence",
        note: "Note",
        instructions: "Payment Instructions",
        orderId: "Order ID",
        amount: "Amount",
        transactionId: "UPI Transaction ID *",
        transactionPlaceholder: "Enter 12-digit UTR/Transaction ID",
        transactionValidation: "Transaction ID must be at least 12 characters",
        accountInformation: "Account Information",
        accountType: "Account Type",
        memberSince: "Member Since",
        userId: "User ID",
        changePassword: "Change Password",
        activeRole: "Active Role",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm New Password",
        businessName: "Business Name",
        businessType: "Business Type",
        businessDescription: "Business Description",
        noProducts: "No products available",
        noCrops: "No crops available",
        noTools: "No tools available",
        loadingOrders: "Loading orders...",
        emptyOrders: "No orders yet. Start shopping!",
        paymentPaid: "💳 PAID",
        paymentPending: "💰 Payment Pending",
        orderFiltersStatus: "Order Status",
        orderFiltersPayment: "Payment Status",
        orderFiltersSort: "Sort By",
        orderFiltersShow: "Show Active Only",
        showCount: "Showing",
        of: "of",
        orders: "orders",
      },
    },
    landing: {
      pill: "Smart agriculture ecosystem",
      heroTitle: "Grow faster with",
      heroHighlight: "AgriEase",
      heroDescription:
        "A single platform for equipment rentals, agri-input purchases, and AI-powered crop disease detection designed for real farm workflows.",
      stats: {
        verifiedFarmers: "Verified Farmers",
        supplierListings: "Supplier Listings",
        onTimeDelivery: "On-Time Delivery",
        supportAvailability: "Support Availability",
      },
      features: {
        pill: "Why AgriEase",
        heading: "Purpose-built tools for modern agriculture",
        description:
          "Structured workflows, trusted suppliers, and AI insights so teams can act quickly with confidence.",
        highlights: {
          equipment: {
            title: "Equipment Access",
            text: "Book modern equipment on flexible schedules without high upfront cost.",
          },
          marketplace: {
            title: "Input Marketplace",
            text: "Buy verified seeds, nutrients, and crop-care products from trusted suppliers.",
          },
          ai: {
            title: "AI Disease Detection",
            text: "Upload crop photos and receive instant diagnosis with practical treatment tips.",
          },
        },
      },
      workflow: {
        pill: "How it works",
        heading: "Get started in three clear steps",
        steps: {
          account: {
            title: "Create Your Account",
            detail: "Join as farmer or supplier in under two minutes.",
          },
          discover: {
            title: "Discover Services",
            detail: "Browse products, equipment, and AI crop health tools.",
          },
          manage: {
            title: "Manage Everything",
            detail: "Track bookings, orders, delivery, and payments in one dashboard.",
          },
        },
      },
      cta: {
        pill: "Start today",
        heading: "Bring your farm operations into one reliable platform",
        text: "Improve decisions, reduce delays, and keep your crop lifecycle data connected from field to delivery.",
        button: "Create Free Account",
      },
      footer: {
        loginLink: "Already a member? Login",
      },
    },
    login: {
      title: "Sign in",
      subtitle: "Welcome back to AgriEase.",
      successGreeting: "Welcome back",
      emailLabel: "Email",
      passwordLabel: "Password",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "Enter your password",
      missingFields: "Please enter email and password",
      errorGeneric: "Invalid credentials",
      submit: "Login",
      createAccountCta: "Create an account",
      newHere: "New here?",
      registerLink: "Register",
    },
    register: {
      title: "Join AgriEase",
      subtitle: "Connect with farmers and suppliers.",
      nameLabel: "Full Name",
      emailLabel: "Email",
      mobileLabel: "Mobile Number",
      passwordLabel: "Password",
      namePlaceholder: "Full name",
      emailPlaceholder: "Email address",
      mobilePlaceholder: "Mobile number",
      passwordPlaceholder: "Create password",
      missingFields: "Please fill all required fields and select a role.",
      success: "Registration successful. Please login.",
      errorGeneric: "An error occurred during registration. Try again.",
      submit: "Create Account",
      ghostCta: "Already have an account? Sign in",
    },
    dashboard: {
      nav: {
        home: "Home",
        products: "Products",
        equipment: "Equipment",
        orders: "Orders",
        tools: "Tools",
        crops: "Crops",
        market: "Market",
        disease: "Disease",
        cart: "Cart",
        profile: "Profile",
      },
    },
    footer: {
      tagline: "Empowering farmers with technology.",
      rights: "All rights reserved.",
    },
    messages: {
      cartEmpty: "Your cart is empty",
      requiredFields: "Please fill all required fields",
      selectImage: "Please upload leaf image",
      predictionFailed: "Prediction failed. Backend not responding.",
      loadOrdersError: "Failed to load orders",
      updateStatusError: "Failed to update status",
      sessionExpired: "Session expired. Please logout and login again.",
      paymentEnterTxn: "Please enter transaction ID",
      paymentTxnLength: "Transaction ID must be at least 12 characters",
      paymentConfirmError: "Failed to confirm payment. Please try again.",
      paymentConfirmed: "Payment confirmed! Waiting for supplier confirmation.",
      imageTooLarge: "Image size should be less than 2MB",
      imageType: "Please select an image file",
      imageReadError: "Failed to read image file",
      profileUpdated: "Profile updated successfully!",
      profileUpdateError: "Failed to update profile",
      passwordMismatch: "New passwords do not match",
      passwordLength: "Password must be at least 6 characters",
      passwordChanged: "Password changed successfully!",
      selectRentalDates: "Select rental dates to proceed",
      endDateInvalid: "End date must be after start date",
      equipmentReserved: "Equipment reserved in cart",
      loadEquipmentError: "Unable to load equipment. Please try again.",
      loadProductsError: "Failed to load products",
      authFailed: "Authentication failed. Please log in again.",
      clearCompletedNone: "No completed orders to clear",
      clearCompletedError: "Failed to clear completed orders",
      unableSync: "Unable to sync with server. Showing cached data.",
      uploadingImage: "Uploading image...",
      roleSwitchFailed: "Unable to switch profile. Please try again.",
    },
    status: {
      pending: "PENDING",
      confirmed: "CONFIRMED",
      delivered: "DELIVERED",
      cancelled: "CANCELLED",
      healthy: "Healthy",
      monitor: "Monitor",
      attention: "Needs Attention",
    },
    farmer: {
      checkout: {
        title: "Checkout",
        subtitle: "Complete your order",
        alertText: "After payment, your order stays PENDING until supplier confirmation.",
        confirmTitle: "Confirm your order?",
        confirmItems: "Items",
        confirmTotal: "Total Amount",
        confirmPayment: "Payment Method",
        confirmDelivery: "Delivery to",
        confirmCta: "Click OK to place order",
        upiOption: "UPI QR Code",
        codOption: "Cash on Delivery",
        emptyTitle: "Your cart is empty",
        emptyAction: "Continue Shopping",
        toastSuccess: "Order placed. Waiting for supplier confirmation.",
        toastError: "Failed to place order",
      },
      crops: {
        title: "Buy Crops",
        subtitle: "Fresh inputs curated by suppliers.",
        empty: "No crops available",
      },
      market: {
        title: "Marketplace",
        subtitle: "Add supplies and place orders in minutes.",
        empty: "No products available",
      },
      home: {
        heroSubtitle: "Stay on top of your fields, equipment, and market activity from one screen.",
        heroGreetingPrefix: "Welcome back",
        refresh: "Refresh data",
        addFarmSize: "Add in profile",
        stat: {
          farmSize: { label: "Farm Size", helper: "Your cultivated land" },
          avgHealth: { label: "Avg Health", helper: "Crop vitality" },
          marketOrders: { label: "Market Orders", helper: "Placed this season" },
          rentals: { label: "Active Rentals", helper: "Equipment on field" },
        },
        quick: {
          market: { title: "Browse Market", subtitle: "Seeds, inputs and supplies" },
          tools: { title: "Rent Equipment", subtitle: "Book verified machines" },
          disease: { title: "Disease Detection", subtitle: "AI crop scans" },
          orders: { title: "My Orders", subtitle: "Track deliveries" },
        },
        cropsSection: {
          kicker: "Crop Health Summary",
          title: "Monitor your fields",
          cta: "View all →",
          acres: "acres",
          statuses: {
            healthy: "Healthy",
            monitor: "Monitor",
            attention: "Attention",
          },
        },
      },
      disease: {
        title: "Plant Disease Detection",
        subtitle: "Upload a leaf image to detect disease.",
        uploadLabel: "Upload leaf image",
        button: "Detect Disease",
        description: "Description",
        prevention: "Prevention",
        confidence: "Confidence",
        buyLink: "Buy Recommended Supplement",
      },
      orders: {
        title: "My Orders",
        subtitle: "Track your order and booking history",
        empty: "No orders yet. Start shopping!",
        toastCancelled: "Order cancelled successfully",
        cancelling: "Cancelling...",
        status: {
          pendingPaid: "Waiting for supplier confirmation",
          pendingUnpaid: "Pending payment & supplier confirmation",
          confirmed: "Confirmed by supplier - Being prepared",
          delivered: "Delivered",
          cancelled: "Cancelled",
        },
      },
      payment: {
        title: "Complete Payment",
        subtitle: "Scan QR code to pay via UPI",
        note: "After payment, your order will be PENDING until the supplier confirms it.",
        instructionsTitle: "Payment Instructions:",
        steps: {
          one: "Open any UPI app (GPay, PhonePe, Paytm, BHIM, etc.)",
          two: 'Tap "Scan QR" and scan the QR code above',
          three: "Verify the amount:",
          four: "Complete the payment using your UPI PIN",
          five: "Copy the 12-digit Transaction/UTR ID from your app",
          six: 'Enter the Transaction ID below and click "Confirm Payment"',
        },
        amountPrefix: "INR",
        button: "Confirm Payment",
        back: "Back to Cart",
      },
      profile: {
        title: "My Profile",
        subtitle: "Manage your account information",
        role: "Farmer",
        avatarHint: 'Click "Edit Profile" to change photo',
        changePhoto: "Change Photo",
        removePhoto: "Remove",
        statsError: "Unable to sync stats right now. Showing last known values.",
        accountStatsTitle: "Account Statistics",
        stats: {
          totalOrders: "Market Orders",
          equipmentBookings: "Equipment Bookings",
          activeBookings: "Active Rentals",
          diseaseScans: "Disease Scans",
          activeNow: "Active now",
        },
        placeholders: {
          phone: "Enter phone number",
          address: "Enter your address",
          farmSize: "e.g., 5 acres",
          cropTypes: "e.g., Rice, Wheat, Vegetables",
        },
        form: {
          farmSizeLabel: "Farm Size (in acres)",
          cropTypesLabel: "Crop Types",
        },
      },
      account: {
        title: "My Profile",
        subtitle: "Manage your account information",
        role: "Farmer",
      },
      tools: {
        title: "Rent Tools",
        subtitle: "Reserve equipment with flexible dates.",
        loading: "Loading equipment...",
        empty: "No tools available",
        available: "Available",
        unavailable: "Not Available",
      },
    },
  },
  mr: {
    common: {
      brandName: "AgriEase",
      brandAlt: "अॅग्रीईज - स्मार्ट शेतीचे भविष्य",
      login: "लॉगिन",
      register: "नोंदणी करा",
      joinFarmer: "शेतकरी म्हणून सामील व्हा",
      joinSupplier: "पुरवठादार म्हणून सामील व्हा",
      alreadyAccount: "आधीच खाते आहे",
      alreadyMember: "आधीच सदस्य आहात? लॉगिन",
      createAccount: "खाते तयार करा",
      createFreeAccount: "विनामूल्य खाते तयार करा",
      language: "भाषा",
      farmer: "शेतकरी",
      supplier: "पुरवठादार",
      logout: "लॉगआउट",
      actions: {
        browseMarket: "मार्केट पहा",
        checkout: "चेकआउट",
        clearCart: "कार्ट रिकामे करा",
        addToCart: "कार्टमध्ये जोडा",
        remove: "काढून टाका",
        continueShopping: "खरेदी सुरू ठेवा",
        refresh: "डेटा रीफ्रेश करा",
        viewAll: "सर्व पहा →",
        editProfile: "प्रोफाइल संपादित करा",
        saveChanges: "बदल जतन करा",
        cancel: "रद्द करा",
        cancelOrder: "ऑर्डर रद्द करा",
        confirm: "निश्चित करा",
        markDelivered: "डिलिव्हर झाले म्हणून चिन्हांकित करा",
        removeHistory: "इतिहासातून काढा",
        clearFilters: "फिल्टर्स काढा",
        clearCompleted: "संपलेल्या ऑर्डर्स काढा",
        showActive: "फक्त सक्रिय दाखवा",
        activeOnly: "✓ फक्त सक्रिय ऑर्डर्स",
        placeOrder: "ऑर्डर करा",
        processing: "प्रक्रिया सुरू...",
        detectDisease: "रोग शोधा",
        confirmPayment: "पेमेंट निश्चित करा",
        paymentConfirmed: "पेमेंट निश्चित झाले",
        backToCart: "कार्टकडे परत",
        addProduct: "+ उत्पादन जोडा",
        addEquipment: "+ उपकरण जोडा",
        updateProduct: "उत्पादन अपडेट करा",
        updateEquipment: "उपकरण अपडेट करा",
        delete: "हटवा",
        edit: "संपादित करा",
        markAvailable: "उपलब्ध दाखवा",
        markUnavailable: "उपलब्ध नाही दाखवा",
        switchProfile: "प्रोफाइल बदला",
        switchToFarmer: "शेतकरी डॅशबोर्डवर जा",
        switchToSupplier: "पुरवठादार डॅशबोर्डवर जा",
      },
      labels: {
        shoppingCart: "खरेदी कार्ट",
        cartSubtitle: "चेकआउटपूर्वी वस्तू तपासा आणि व्यवस्थापित करा",
        cartEmpty: "तुमचा कार्ट रिकामा आहे",
        product: "उत्पादन",
        crop: "पीक",
        equipmentRental: "उपकरण भाडे",
        rate: "दर",
        duration: "कालावधी",
        dates: "तारखा",
        orderSummary: "ऑर्डर सारांश",
        totalItems: "एकूण वस्तू",
        total: "एकूण",
        paymentMethod: "पेमेंट पद्धत",
        shippingDetails: "शिपिंग तपशील",
        fullName: "पूर्ण नाव",
        email: "ईमेल",
        phoneNumber: "फोन क्रमांक",
        address: "पत्ता",
        city: "शहर",
        state: "राज्य",
        pincode: "पिनकोड",
        qty: "प्रमाण",
        important: "महत्त्वाचे",
        pendingNote: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत तुमची ऑर्डर PENDING राहील.",
        items: "वस्तू",
        customerDetails: "ग्राहक तपशील",
        shippingAddress: "शिपिंग पत्ता",
        orderDate: "ऑर्डर तारीख",
        status: "स्थिती",
        paymentStatus: "पेमेंट स्थिती",
        available: "उपलब्ध",
        unavailable: "उपलब्ध नाही",
        lastSynced: "शेवटचे सिंक",
        description: "वर्णन",
        prevention: "प्रतिबंध",
        confidence: "विश्वास पातळी",
        note: "टिप",
        instructions: "पेमेंट सूचना",
        orderId: "ऑर्डर क्रमांक",
        amount: "रक्कम",
        transactionId: "UPI व्यवहार क्रमांक *",
        transactionPlaceholder: "१२ अंकी UTR/Transaction ID भरा",
        transactionValidation: "Transaction ID किमान १२ अक्षरांचा हवा",
        accountInformation: "खाते माहिती",
        accountType: "खात्याचा प्रकार",
        memberSince: "सदस्यता दिनांक",
        userId: "वापरकर्ता क्रमांक",
        changePassword: "पासवर्ड बदला",
        activeRole: "सक्रिय भूमिका",
        currentPassword: "सध्याचा पासवर्ड",
        newPassword: "नवीन पासवर्ड",
        confirmPassword: "नवीन पासवर्ड पुन्हा भरा",
        businessName: "व्यवसायाचे नाव",
        businessType: "व्यवसाय प्रकार",
        businessDescription: "व्यवसाय वर्णन",
        noProducts: "कोणतीही उत्पादने उपलब्ध नाहीत",
        noCrops: "कोणतीही पिके उपलब्ध नाहीत",
        noTools: "कोणतीही साधने उपलब्ध नाहीत",
        loadingOrders: "ऑर्डर्स लोड होत आहेत...",
        emptyOrders: "अद्याप कोणतीही ऑर्डर नाही. खरेदी सुरू करा!",
        paymentPaid: "💳 पेमेंट झाले",
        paymentPending: "💰 पेमेंट प्रलंबित",
        orderFiltersStatus: "ऑर्डर स्थिती",
        orderFiltersPayment: "पेमेंट स्थिती",
        orderFiltersSort: "क्रम लावा",
        orderFiltersShow: "फक्त सक्रिय दाखवा",
        showCount: "दाखवत आहोत",
        of: "पैकी",
        orders: "ऑर्डर्स",
      },
    },
    landing: {
      pill: "स्मार्ट शेती इकोसिस्टम",
      heroTitle: "अधिक वेगाने वाढवा",
      heroHighlight: "AgriEase",
      heroDescription:
        "उपकरण भाडे, कृषी इनपुट खरेदी आणि एआय रोग निदानासाठी एकच प्लॅटफॉर्म.",
      stats: {
        verifiedFarmers: "सत्यापित शेतकरी",
        supplierListings: "पुरवठादार सूची",
        onTimeDelivery: "वेळेवर वितरण",
        supportAvailability: "२४/७ समर्थन",
      },
      features: {
        pill: "अॅग्रीईज का?",
        heading: "आधुनिक शेतीसाठी तयार केलेली साधने",
        description:
          "संरचित वर्कफ्लो, विश्वासू पुरवठादार आणि एआय इनसाइट्समुळे टीमला जलद निर्णय घेता येतात.",
        highlights: {
          equipment: {
            title: "उपकरण उपलब्धता",
            text: "मोठा खर्च न करता आधुनिक उपकरणे सोयीच्या वेळांना बुक करा.",
          },
          marketplace: {
            title: "इनपुट मार्केटप्लेस",
            text: "विश्वासार्ह पुरवठादारांकडून बी-बियाणे, पोषक तत्त्वे आणि पिक संरक्षण खरेदी करा.",
          },
          ai: {
            title: "एआय रोग निदान",
            text: "पीकांचे फोटो अपलोड करा आणि त्वरित निदान तसेच उपचाराचा सल्ला मिळवा.",
          },
        },
      },
      workflow: {
        pill: "कसे कार्य करते",
        heading: "फक्त तीन टप्प्यात सुरुवात",
        steps: {
          account: {
            title: "तुमचे खाते तयार करा",
            detail: "२ मिनिटांत शेतकरी किंवा पुरवठादार म्हणून सामील व्हा.",
          },
          discover: {
            title: "सेवा शोधा",
            detail: "उत्पादने, उपकरणे आणि एआय पीक आरोग्य साधने ब्राउझ करा.",
          },
          manage: {
            title: "सर्वकाही सांभाळा",
            detail: "बुकिंग, ऑर्डर, वितरण आणि पेमेंट एकाच डॅशबोर्डवर ट्रॅक करा.",
          },
        },
      },
      cta: {
        pill: "आजच सुरू करा",
        heading: "आपली शेती ऑपरेशन्स एका विश्वासार्ह प्लॅटफॉर्मवर आणा",
        text: "निर्णय सुधारवा, विलंब कमी करा आणि शेतापासून वितरणापर्यंतची माहिती जोडलेली ठेवा.",
        button: "विनामूल्य खाते तयार करा",
      },
      footer: {
        loginLink: "आधीच सदस्य आहात? लॉगिन",
      },
    },
    login: {
      title: "लॉगिन करा",
      subtitle: "अॅग्रीईजवर परत स्वागत आहे.",
      successGreeting: "पुन्हा स्वागत आहे",
      emailLabel: "ईमेल",
      passwordLabel: "पासवर्ड",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "तुमचा पासवर्ड टाका",
      missingFields: "कृपया ईमेल आणि पासवर्ड भरा",
      errorGeneric: "चुकीची ओळख माहिती",
      submit: "लॉगिन",
      createAccountCta: "खाते तयार करा",
      newHere: "इथे नवीन आहात?",
      registerLink: "नोंदणी करा",
    },
    register: {
      title: "अॅग्रीईजमध्ये सामील व्हा",
      subtitle: "शेतकरी आणि पुरवठादार यांना जोडा.",
      nameLabel: "पूर्ण नाव",
      emailLabel: "ईमेल",
      mobileLabel: "मोबाइल क्रमांक",
      passwordLabel: "पासवर्ड",
      namePlaceholder: "पूर्ण नाव",
      emailPlaceholder: "ईमेल पत्ता",
      mobilePlaceholder: "मोबाइल क्रमांक",
      passwordPlaceholder: "पासवर्ड तयार करा",
      missingFields: "कृपया सर्व माहिती भरा आणि भूमिका निवडा.",
      success: "नोंदणी यशस्वी. कृपया लॉगिन करा.",
      errorGeneric: "नोंदणीदरम्यान त्रुटी आली. पुन्हा प्रयत्न करा.",
      submit: "खाते तयार करा",
      ghostCta: "आधीच खाते आहे? लॉगिन करा",
    },
    dashboard: {
      nav: {
        home: "मुख्यपृष्ठ",
        products: "उत्पादने",
        equipment: "उपकरणे",
        orders: "ऑर्डर्स",
        tools: "साधने",
        crops: "पिके",
        market: "बाजार",
        disease: "रोग",
        cart: "कार्ट",
        profile: "प्रोफाइल",
      },
    },
    footer: {
      tagline: "तंत्रज्ञानाद्वारे शेतकऱ्यांना सामर्थ्य द्या.",
      rights: "सर्व हक्क राखीव.",
    },
    messages: {
      cartEmpty: "तुमचा कार्ट रिकामा आहे",
      requiredFields: "कृपया सर्व आवश्यक माहिती भरा",
      selectImage: "कृपया पानाचा फोटो अपलोड करा",
      predictionFailed: "भाकीत अयशस्वी. बॅकएंड प्रतिसाद देत नाही.",
      loadOrdersError: "ऑर्डर्स लोड करण्यात अयशस्वी",
      updateStatusError: "स्थिती अपडेट करता आली नाही",
      sessionExpired: "सेशन संपले. कृपया लॉगआउट करून पुन्हा लॉगिन करा.",
      paymentEnterTxn: "कृपया व्यवहार क्रमांक भरा",
      paymentTxnLength: "Transaction ID किमान 12 अक्षरांचा हवा",
      paymentConfirmError: "पेमेंट निश्चित करण्यात अयशस्वी. पुन्हा प्रयत्न करा.",
      paymentConfirmed: "पेमेंट निश्चित! पुरवठादार पुष्टीची प्रतीक्षा.",
      imageTooLarge: "प्रतिमेचा आकार 2MB पेक्षा कमी असावा",
      imageType: "कृपया इमेज फाइल निवडा",
      imageReadError: "प्रतिमा वाचताना त्रुटी आली",
      profileUpdated: "प्रोफाइल यशस्वीरीत्या अपडेट केले!",
      profileUpdateError: "प्रोफाइल अपडेट करता आले नाही",
      passwordMismatch: "नवीन पासवर्ड जुळत नाहीत",
      passwordLength: "पासवर्ड किमान 6 अक्षरांचा असणे आवश्यक आहे",
      passwordChanged: "पासवर्ड यशस्वीरीत्या बदलला!",
      selectRentalDates: "कृपया भाड्याच्या तारखा निवडा",
      endDateInvalid: "शेवटची तारीख सुरुवातीच्या तारखेनंतरची असावी",
      equipmentReserved: "उपकरण कार्टमध्ये राखीव केले",
      loadEquipmentError: "उपकरणे लोड करता आली नाहीत. पुन्हा प्रयत्न करा.",
      loadProductsError: "उत्पादने लोड करण्यात अयशस्वी",
      authFailed: "प्रमाणीकरण अयशस्वी. कृपया पुन्हा लॉगिन करा.",
      clearCompletedNone: "काढण्यासाठी पूर्ण झालेल्या ऑर्डर्स नाहीत",
      clearCompletedError: "संपलेल्या ऑर्डर्स काढता आल्या नाहीत",
      unableSync: "सर्व्हरशी सिंक होत नाही. शेवटचा जतन केलेला डेटा दाखवत आहोत.",
      uploadingImage: "प्रतिमा अपलोड करत आहे...",
      roleSwitchFailed: "प्रोफाइल बदलता आले नाही. पुन्हा प्रयत्न करा.",
    },
    status: {
      pending: "प्रलंबित",
      confirmed: "निश्चित",
      delivered: "वितरित",
      cancelled: "रद्द",
      healthy: "आरोग्यपूर्ण",
      monitor: "नजर ठेवा",
      attention: "काळजी",
    },
    farmer: {
      checkout: {
        title: "चेकआउट",
        subtitle: "आपली ऑर्डर पूर्ण करा",
        alertText: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत तुमची ऑर्डर PENDING राहील.",
        confirmTitle: "आपली ऑर्डर निश्चित करायची?",
        confirmItems: "वस्तू",
        confirmTotal: "एकूण रक्कम",
        confirmPayment: "पेमेंट पद्धत",
        confirmDelivery: "वितरण पत्ता",
        confirmCta: "ऑर्डर करण्यासाठी OK क्लिक करा",
        upiOption: "UPI QR कोड",
        codOption: "डिलिव्हरीवर रोख",
        emptyTitle: "तुमचा कार्ट रिकामा आहे",
        emptyAction: "खरेदी सुरू ठेवा",
        toastSuccess: "ऑर्डर तयार झाली. पुरवठादाराच्या पुष्टीची प्रतीक्षा.",
        toastError: "ऑर्डर करता आली नाही",
      },
      crops: {
        title: "पिके खरेदी करा",
        subtitle: "पुरवठादारांनी निवडलेले ताजे इनपुट.",
        empty: "कोणतीही पिके उपलब्ध नाहीत",
      },
      market: {
        title: "मार्केटप्लेस",
        subtitle: "काही मिनिटांत पुरवठा जोडा आणि ऑर्डर करा.",
        empty: "कोणतीही उत्पादने उपलब्ध नाहीत",
      },
      home: {
        heroSubtitle: "एका स्क्रीनवर शेत, उपकरणे आणि मार्केट क्रियाकलाप सांभाळा.",
        heroGreetingPrefix: "पुन्हा स्वागत आहे",
        refresh: "डेटा रीफ्रेश करा",
        addFarmSize: "प्रोफाइलमध्ये जोडा",
        stat: {
          farmSize: { label: "शेतीचा आकार", helper: "तुमची लागवड केलेली जमीन" },
          avgHealth: { label: "सरासरी आरोग्य", helper: "पीक जोम" },
          marketOrders: { label: "मार्केट ऑर्डर्स", helper: "या हंगामात दिल्या" },
          rentals: { label: "सक्रिय भाडे", helper: "शेतातील उपकरणे" },
        },
        quick: {
          market: { title: "मार्केट पहा", subtitle: "बियाणे, इनपुट्स आणि पुरवठा" },
          tools: { title: "उपकरणे भाड्याने घ्या", subtitle: "विश्वासार्ह मशीन बुक करा" },
          disease: { title: "रोग निदान", subtitle: "एआय पीक स्कॅन" },
          orders: { title: "माझ्या ऑर्डर्स", subtitle: "डिलिव्हरी ट्रॅक करा" },
        },
        cropsSection: {
          kicker: "पीक आरोग्य सारांश",
          title: "आपली शेतं पाहा",
          cta: "सर्व पहा →",
          acres: "एकर",
          statuses: {
            healthy: "आरोग्यपूर्ण",
            monitor: "नजर ठेवा",
            attention: "काळजी",
          },
        },
      },
      disease: {
        title: "वनस्पती रोग निदान",
        subtitle: "रोग ओळखण्यासाठी पानाचा फोटो अपलोड करा.",
        uploadLabel: "पानाचा फोटो अपलोड करा",
        button: "रोग शोधा",
        description: "वर्णन",
        prevention: "प्रतिबंध",
        confidence: "विश्वास पातळी",
        buyLink: "शिफारस केलेले पूरक खरेदी करा",
      },
      orders: {
        title: "माझ्या ऑर्डर्स",
        subtitle: "आपल्या ऑर्डर आणि बुकिंग इतिहासावर नजर ठेवा",
        empty: "अद्याप कोणतीही ऑर्डर नाही. खरेदी सुरू करा!",
        toastCancelled: "ऑर्डर यशस्वीरीत्या रद्द केली",
        cancelling: "रद्द करत आहे...",
        status: {
          pendingPaid: "पुरवठादार पुष्टीची प्रतीक्षा",
          pendingUnpaid: "पेमेंट व पुष्टी प्रलंबित",
          confirmed: "पुरवठादाराने निश्चित केली - तयारीत",
          delivered: "वितरित",
          cancelled: "रद्द",
        },
      },
      payment: {
        title: "पेमेंट पूर्ण करा",
        subtitle: "UPI द्वारे पैसे भरण्यासाठी QR कोड स्कॅन करा",
        note: "पेमेंटनंतर पुरवठादार खात्री करेपर्यंत ऑर्डर PENDING राहील.",
        instructionsTitle: "पेमेंट सूचना:",
        steps: {
          one: "कोणतीही UPI अॅप (GPay, PhonePe, Paytm, BHIM इ.) उघडा",
          two: '"Scan QR" टॅप करा आणि वरील QR कोड स्कॅन करा',
          three: "रक्कम तपासा:",
          four: "तुमच्या UPI PIN ने पेमेंट पूर्ण करा",
          five: "अॅपमधील 12 अंकी Transaction/UTR ID कॉपी करा",
          six: 'Transaction ID खाली भरा आणि "Confirm Payment" क्लिक करा',
        },
        amountPrefix: "INR",
        button: "पेमेंट निश्चित करा",
        back: "कार्टकडे परत",
      },
      profile: {
        title: "माझे प्रोफाइल",
        subtitle: "आपली खाते माहिती सांभाळा",
        role: "शेतकरी",
        avatarHint: 'फोटो बदलण्यासाठी "प्रोफाइल संपादित करा" क्लिक करा',
        changePhoto: "फोटो बदला",
        removePhoto: "काढा",
        statsError: "स्टॅट्स सिंक होत नाहीत. शेवटचे मूल्य दाखवत आहोत.",
        accountStatsTitle: "खाते आकडेवारी",
        stats: {
          totalOrders: "मार्केट ऑर्डर्स",
          equipmentBookings: "उपकरण बुकिंग",
          activeBookings: "सक्रिय भाडे",
          diseaseScans: "रोग स्कॅन",
          activeNow: "सध्या सक्रिय",
        },
        placeholders: {
          phone: "फोन क्रमांक भरा",
          address: "तुमचा पत्ता भरा",
          farmSize: "उदा. 5 एकर",
          cropTypes: "उदा. भात, गहू, भाजीपाला",
        },
        form: {
          farmSizeLabel: "शेतीचा आकार (एकरमध्ये)",
          cropTypesLabel: "पीक प्रकार",
        },
      },
      account: {
        title: "माझे प्रोफाइल",
        subtitle: "आपली खाते माहिती सांभाळा",
        role: "शेतकरी",
      },
      tools: {
        title: "साधने भाड्याने घ्या",
        subtitle: "लवचिक तारखांसह उपकरणे आरक्षित करा.",
        loading: "उपकरणे लोड होत आहेत...",
        empty: "कोणतीही साधने उपलब्ध नाहीत",
        available: "उपलब्ध",
        unavailable: "उपलब्ध नाही",
      },
    },
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const AVAILABLE_LANGUAGES = [
  { code: "en", label: "English" },
  { code: "mr", label: "मराठी" },
];

function resolveTranslation(dictionary, key) {
  return key.split(".").reduce((acc, part) => (acc ? acc[part] : undefined), dictionary);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") {
      return "en";
    }
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored && translations[stored]) {
      return stored;
    }
    return window.navigator?.language?.toLowerCase().startsWith("mr") ? "mr" : "en";
  });

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const value = useMemo(() => {
    const translate = (key) => {
      const localized = resolveTranslation(translations[language], key);
      if (localized) {
        return localized;
      }
      return resolveTranslation(translations.en, key) ?? key;
    };

    return {
      language,
      setLanguage,
      t: translate,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
